'use strict';
const crypto=require('node:crypto'),assert=require('node:assert/strict');
const PACKAGE_ID='MAT-EVENTCARD-NATIVE-COMPONENT-PATHS-PROJECTION-R2',PARENT_PACKAGE_ID='MAT-EVENTCARD-NATIVE-COMPONENT-PATHS-REPAIR-R1';
const FILE_ID='40e06342-8830-80d6-8008-8fc8a3a4cd4f',PAGE_ID='c16498cb-b51d-8030-8008-904bd8fc9c53',COLLECTION_ID='313fb1ed-0d5c-8095-8008-9108df52b2ce',COLLECTION_NAME='KenigEvents · G12 bounded L0-L3',LEGACY='KenigEvents / G19 / EventCard 8006 / Accepted';
const PATHS={dL:'KenigEvents / EventCard / Leaves / Desktop',mL:'KenigEvents / EventCard / Leaves / Mobile',dC:'KenigEvents / EventCard / Cases / Desktop',mC:'KenigEvents / EventCard / Cases / Mobile'};
const SPECS=[
['event.media-frame.desktop.8006','dL'],['event.meta.event-type.desktop.8006','dL'],['event.meta.admission.desktop.8006','dL'],['event.action.not-interested.desktop.8006','dL'],['event.action.calendar.desktop.8006','dL'],['event.action.share.desktop.8006','dL'],['event.action.like.desktop.8006','dL'],
['event.media-frame.mobile.8006','mL'],['event.meta.event-type.mobile.8006','mL'],['event.meta.admission.mobile.8006','mL'],['event.action.not-interested.mobile.8006','mL'],['event.action.calendar.mobile.8006','mL'],['event.action.share.mobile.8006','mL'],['event.action.like.mobile.8006','mL'],
['eventcard.desktop-wide-calendar.8006','dC','313fb1ed-0d5c-8095-8008-912d51452f89','313fb1ed-0d5c-8095-8008-912c45090653',7,false],
['eventcard.desktop-packed-calendar-absent.2182','dC','313fb1ed-0d5c-8095-8008-916b0b931d1f','313fb1ed-0d5c-8095-8008-914c76615924',6,true],
['eventcard.mobile-wide-calendar.8006','mC','313fb1ed-0d5c-8095-8008-916bb0cb7843','313fb1ed-0d5c-8095-8008-916b340de148',7,true],
['eventcard.mobile-packed-calendar-absent.2182','mC','313fb1ed-0d5c-8095-8008-916be7e9352d','313fb1ed-0d5c-8095-8008-916bd0ab6c98',6,true]
].map(([name,group,componentId=null,mainId=null,links=0,legacy=false])=>({name,group,componentId,mainId,links,legacy,kind:links?'case':'leaf'}));
class Stop extends Error{constructor(code,unknown=false){super(code);this.code=code;this.unknownOutcome=unknown;this.retryAllowed=false}}
const fail=(c,u=false)=>{throw new Stop(c,u)},canon=v=>Array.isArray(v)?`[${v.map(canon)}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canon(v[k])}`)}}`:JSON.stringify(v),hash=v=>crypto.createHash('sha256').update(canon(v)).digest('hex'),str=v=>{if(typeof v!=='string')fail('PATHS_PLUGIN_DATA_NOT_STRING');return v};
function coll(a){const c=a.collection(COLLECTION_ID);if(c.rootId!==COLLECTION_ID||c.name!==COLLECTION_NAME||c.roots!==1||c.children!==18||c.components!==18||c.detached||c.clones||c.recreated||c.validation.length||c.protected==null)fail('PATHS_COLLECTION_DRIFT');return c}
function components(a){const inv=a.components();if(inv.length!==18)fail('PATHS_COMPONENT_CENSUS_DRIFT');const rows=SPECS.map(s=>{const m=inv.filter(x=>x.name===s.name&&x.main.name===s.name);if(m.length!==1)fail('PATHS_COMPONENT_ID_CARDINALITY');const x=m[0];if(!x.id||!x.main.id)fail('PATHS_COMPONENT_OR_MAIN_ID_MISSING');if(s.componentId&&x.id!==s.componentId)fail('PATHS_PINNED_COMPONENT_ID_DRIFT');if(s.mainId&&x.main.id!==s.mainId)fail('PATHS_PINNED_MAIN_ID_DRIFT');const expected=PATHS[s.group],allowed=x.path===''||x.path===expected||(s.legacy&&x.path===LEGACY);if(!allowed)fail('PATHS_UNKNOWN_CURRENT_PATH');return{semanticName:s.name,kind:s.kind,componentId:x.id,mainId:x.main.id,componentName:x.name,mainName:x.main.name,currentPath:x.path,expectedCanonicalPath:expected,linkedCount:s.links}});
 if(new Set(rows.map(x=>x.componentId)).size!==18)fail('PATHS_DUPLICATE_COMPONENT_ID');if(new Set(rows.map(x=>x.mainId)).size!==18)fail('PATHS_DUPLICATE_MAIN_ID');return rows}
function links(a,rows){const leaf=new Set(rows.filter(x=>x.kind==='leaf').map(x=>x.componentId)),out=[];for(const c of rows.filter(x=>x.kind==='case')){const xs=a.links(c.mainId);if(xs.length!==c.linkedCount)fail('PATHS_LINKED_COUNT_DRIFT');for(const x of xs){if(!x.id||!x.componentId||!x.parentMainId||!x.parentCaseComponentId)fail('PATHS_LINKED_ID_MISSING');if(x.parentMainId!==c.mainId||x.parentCaseComponentId!==c.componentId||!leaf.has(x.componentId))fail('PATHS_LINK_RELATION_DRIFT');out.push({...x,caseComponentId:c.componentId,caseMainId:c.mainId})}}if(out.length!==26)fail('PATHS_LINKED_CENSUS_DRIFT');if(new Set(out.map(x=>x.id)).size!==26)fail('PATHS_DUPLICATE_LINKED_ID');return out.sort((x,y)=>x.id.localeCompare(y.id))}
function projectState(a,state='baseline'){const i=a.identity();if(i.fileId!==FILE_ID||i.pageId!==PAGE_ID||!Number.isInteger(i.revision))fail('PATHS_CURRENT_REVISION_MISSING');const c=coll(a),rows=components(a),ls=links(a,rows),count={exact:rows.filter(x=>x.currentPath===x.expectedCanonicalPath).length,empty:rows.filter(x=>x.currentPath==='').length,legacy:rows.filter(x=>x.currentPath===LEGACY).length};if(state==='baseline'&&(count.exact!==0||count.empty!==15||count.legacy!==3))fail('PATHS_BASELINE_COUNTS_DRIFT');if(state==='terminal'&&(count.exact!==18||count.empty||count.legacy))fail('PATHS_TERMINAL_COUNTS_DRIFT');const p={schema:'component-paths-projection-r2',packageId:PACKAGE_ID,revision:i.revision,state,components:rows,componentIds:rows.map(x=>x.componentId).sort(),mainIds:rows.map(x=>x.mainId).sort(),linkedInstances:ls,linkedInstanceIds:ls.map(x=>x.id).sort(),count,protectedCollectionDigest:hash(c.protected),collection:c,mutationFree:true};return{...p,projectionSha256:hash(p),penpotMutations:0}}
const projectEventcardComponentPathsR2=a=>projectState(a,'baseline');
function auth(x,p){if(x?.schema!=='paths-binding-auth-r2'||x.packageId!==PACKAGE_ID||x.parentPackageId!==PARENT_PACKAGE_ID||x.state!=='ACTIVE'||x.authorized!==true||x.cancelled!==false)fail('PATHS_AUTH_MISMATCH');if(x.revision!==p.revision)fail('PATHS_STALE_REVISION');if(x.projectionSha256!==p.projectionSha256)fail('PATHS_STALE_PROJECTION_SHA')}
const identity=p=>({components:p.components.map(x=>[x.semanticName,x.componentId,x.mainId,x.componentName,x.mainName]),links:p.linkedInstances});
async function executeEventcardComponentPathsProjectionR2(a,x){if(a.marker(PACKAGE_ID))fail('PATHS_EXECUTOR_REPLAY_FORBIDDEN');const p=projectEventcardComponentPathsR2(a);auth(x,p);const q=projectEventcardComponentPathsR2(a);if(q.revision!==x.revision||q.projectionSha256!==x.projectionSha256)fail('PATHS_PROJECTION_CHANGED_BEFORE_MUTATION');const before=identity(q);try{await a.atomic(async()=>{for(const r of q.components){if(a.identity().revision!==x.revision)fail('PATHS_STALE_REVISION_DURING_MUTATION');a.setPath(r.componentId,r.expectedCanonicalPath)}})}catch(e){if(e instanceof Stop)throw e;fail('PATHS_TIMEOUT_OR_UNKNOWN_OUTCOME',true)}const t=projectState(a,'terminal');if(t.protectedCollectionDigest!==p.protectedCollectionDigest||canon(identity(t))!==canon(before))fail('PATHS_ID_NAME_LINK_OR_PROTECTED_DRIFT',true);const r={packageId:PACKAGE_ID,state:'PATHS_18_OF_18_PENDING_DISTINCT_READBACK',revision:x.revision,projectionSha256:x.projectionSha256,protectedCollectionDigest:p.protectedCollectionDigest,componentIds:t.componentIds,mainIds:t.mainIds,linkedInstanceIds:t.linkedInstanceIds,pathMutations:18,componentNameMutations:0,mainNameMutations:0,detach:0,clone:0,recreate:0,retryAllowed:false,visualPass:false,wholeEventcardPass:false};a.writeMarker(PACKAGE_ID,str(canon(r)));return r}
function readEventcardComponentPathsSettlementR2(a,r){if(r?.state!=='PATHS_18_OF_18_PENDING_DISTINCT_READBACK'||!a.marker(PACKAGE_ID))fail('PATHS_SETTLEMENT_RECEIPT_REQUIRED');const t=projectState(a,'terminal');if(t.protectedCollectionDigest!==r.protectedCollectionDigest||canon(t.componentIds)!==canon(r.componentIds)||canon(t.mainIds)!==canon(r.mainIds)||canon(t.linkedInstanceIds)!==canon(r.linkedInstanceIds))fail('PATHS_SETTLEMENT_DRIFT');return{state:'PATHS_18_OF_18_READBACK_PASS_PENDING_V0',exact:18,linkedInstances:26,readbackMutations:0,componentNameMutations:0,mainNameMutations:0,detach:0,clone:0,recreate:0,visualPass:false,wholeEventcardPass:false}}
function selfTest(){class A{constructor(){this.rev=178;this.m='';this.token='stable';this.timeout=false;this.rows=SPECS.map((s,n)=>({id:s.componentId||'c'+n,name:s.name,path:s.legacy?LEGACY:'',main:{id:s.mainId||'m'+n,name:s.name}}));this.l=new Map();for(const[n,s]of SPECS.slice(14).entries()){const c=this.rows[14+n],pool=n<2?this.rows.slice(0,7):this.rows.slice(7,14),use=s.links===7?pool:pool.filter((_,i)=>i!==4).slice(0,6);this.l.set(c.main.id,use.map((v,i)=>({id:`l${n}-${i}`,componentId:v.id,parentMainId:c.main.id,parentCaseComponentId:c.id})))}}identity(){return{fileId:FILE_ID,pageId:PAGE_ID,revision:this.rev}}collection(){return{rootId:COLLECTION_ID,name:COLLECTION_NAME,roots:1,children:18,components:18,detached:0,clones:0,recreated:0,validation:[],protected:{token:this.token}}}components(){return structuredClone(this.rows)}links(id){return structuredClone(this.l.get(id)||[])}marker(){return this.m}writeMarker(_,v){this.m=v}async atomic(f){return f()}setPath(id,p){const x=this.rows.find(y=>y.id===id);x.path=p;if(this.timeout)throw Object.assign(new Error('timeout'),{code:'ETIMEDOUT'})}}
 const mk=p=>({schema:'paths-binding-auth-r2',packageId:PACKAGE_ID,parentPackageId:PARENT_PACKAGE_ID,state:'ACTIVE',authorized:true,cancelled:false,revision:p.revision,projectionSha256:p.projectionSha256});
 let a=new A(),p=projectEventcardComponentPathsR2(a);assert.equal(p.componentIds.length,18);assert.equal(p.linkedInstanceIds.length,26);assert.equal(p.projectionSha256,projectEventcardComponentPathsR2(a).projectionSha256);return executeEventcardComponentPathsProjectionR2(a,mk(p)).then(r=>{assert.equal(readEventcardComponentPathsSettlementR2(a,r).exact,18);
 a=new A();p=projectEventcardComponentPathsR2(a);a.rev++;assert.throws(()=>auth(mk(p),projectEventcardComponentPathsR2(a)),e=>e.code==='PATHS_STALE_REVISION');
 a=new A();a.rows.pop();assert.throws(()=>projectEventcardComponentPathsR2(a),e=>e.code==='PATHS_COMPONENT_CENSUS_DRIFT');
 a=new A();a.rows[1].id=a.rows[0].id;assert.throws(()=>projectEventcardComponentPathsR2(a),e=>e.code==='PATHS_DUPLICATE_COMPONENT_ID');
 a=new A();const k=a.rows[15].main.id;a.l.get(k)[0].id=a.l.get(a.rows[14].main.id)[0].id;assert.throws(()=>projectEventcardComponentPathsR2(a),e=>e.code==='PATHS_DUPLICATE_LINKED_ID');
 a=new A();p=projectEventcardComponentPathsR2(a);const x=mk(p);a.token='changed';assert.throws(()=>auth(x,projectEventcardComponentPathsR2(a)),e=>e.code==='PATHS_STALE_PROJECTION_SHA');
 a=new A();p=projectEventcardComponentPathsR2(a);a.timeout=true;return executeEventcardComponentPathsProjectionR2(a,mk(p)).then(()=>fail('EXPECTED'),e=>{assert.equal(e.code,'PATHS_TIMEOUT_OR_UNKNOWN_OUTCOME');assert.equal(e.retryAllowed,false);assert.throws(()=>str({}),e=>e.code==='PATHS_PLUGIN_DATA_NOT_STRING');console.log('PATHS_BINDING_R2_SELF_TEST_PASS 9/9')})})}
if(require.main===module&&process.argv.includes('--self-test'))selfTest().catch(e=>{console.error(e);process.exit(1)});
module.exports={PACKAGE_ID,PARENT_PACKAGE_ID,FILE_ID,PAGE_ID,COLLECTION_ID,COLLECTION_NAME,LEGACY,PATHS,SPECS,Stop,canon,hash,str,projectEventcardComponentPathsR2,executeEventcardComponentPathsProjectionR2,readEventcardComponentPathsSettlementR2};
