'use strict';
const test=require('node:test'),a=require('node:assert/strict');
const v1=require('../../../../scripts/asp-production-conveyor-v3/d0/mat/f0_existing_atlas_layout_repair_v1.js');
const p1=require('../../../../scripts/asp-production-conveyor-v3/d0/mat/f0_existing_atlas_layout_repair_payload_v1.js');
const v2=require('../../../../scripts/asp-production-conveyor-v3/d0/mat/action_nav_atlas_r2_rebind_v2.js');
const p2=require('../../../../scripts/asp-production-conveyor-v3/d0/mat/action_nav_atlas_r2_rebind_payload_v2.js');
const {CONFIG,FOUNDATION,ACTION_ASSETS}=p2,PID='F-ACTION-NAV-ICONS';
const canon=v=>Array.isArray(v)?'['+v.map(canon).join(',')+']':v&&typeof v==='object'?'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canon(v[k])).join(',')+'}':JSON.stringify(v);
const projectionHash=input=>input.length===FOUNDATION.protected.utf8Bytes?FOUNDATION.protected.sha256:input.length===FOUNDATION.source.utf8Bytes?FOUNDATION.source.sha256:null;
p1._setTestHashOverride(projectionHash);p2._setTestHashOverride(projectionHash);
let id=0;
class D{constructor(){this.d=new Map}setSharedPluginData(n,k,v){if(typeof v!=='string')throw Error('PLUGIN_DATA_VALUE_NOT_STRING');this.d.set(n+':'+k,v)}getSharedPluginData(n,k){return this.d.get(n+':'+k)||''}}
class S extends D{constructor(type='board',fixed){super();this.id=fixed||'s'+ ++id;this.type=type;this.name='';this.x=this.y=0;this.width=this.height=128;this.children=[];this.fills=[];this.strokes=[];this._c=null;this._i=false}appendChild(x){if(x.parent)x.parent.children=x.parent.children.filter(y=>y!==x);x.parent=this;this.children.push(x)}remove(){if(this.parent)this.parent.children=this.parent.children.filter(x=>x!==this);this.parent=null}resize(w,h){this.width=w;this.height=h}component(){return this._c}isComponentCopyInstance(){return this._i}async export(){return new Uint8Array([1,2,3])}}
function cloneShape(source){const x=new S(source.type);x.name=source.name;x.x=source.x;x.y=source.y;x.width=source.width;x.height=source.height;x.characters=source.characters;x.content=source.content;x.fills=structuredClone(source.fills);x.strokes=structuredClone(source.strokes);x.d=new Map(source.d);for(const child of source.children)x.appendChild(cloneShape(child));return x}
class C{constructor(m,fixed){this.id=fixed||'c'+ ++id;this.m=m;this.name=this.path='';m._c=this}mainInstance(){return this.m}instance(){const x=cloneShape(this.m);x._c=this;x._i=true;return x}}
class Pg extends D{constructor(fixed){super();this.id=fixed||'p'+ ++id;this.name='';this.root=new S('root',this.id+'r')}}
class F extends D{constructor(){super();this.id=CONFIG.fileId;this.pages=[];this.v=[]}validate(){return[]}async saveVersion(label){const x={id:'v'+ ++id,label};this.v.push(x);return x}async findVersions(){return this.v}}
class P{constructor(){this.created=0;this.pageCreates=0;this.boardCreates=0;this.currentFile=new F;this.currentPage=null;this.library={local:{components:[]}};this.library.local.createComponent=([m])=>{const c=new C(m);this.library.local.components.push(c);return c};this.history={undoBlockBegin:()=>Symbol(),undoBlockFinish:()=>{}}}createPage(){this.created++;this.pageCreates++;const p=new Pg;this.currentFile.pages.push(p);return p}createShapeFromSvg(svg){const x=new S('path');x.content=svg;return x}createBoard(){this.created++;this.boardCreates++;return new S}createText(t){this.created++;const x=new S('text');x.characters=t;return x}async openPage(p){this.currentPage=p}}
function claimV1(){return{schema:'kenigevents.asp-atlas-publish-claim.v1',package_id:PID,logical_writer_id:'/root/publish_r2',publish_identity:'/root/d0_publish_atlas_r2',run_id:'run-r1',lease_token:'lease-r1',cancel_token:'cancel-r1',adapter_id:`D0-MAT-${PID}-ATLAS-R1`,adapter_sha256:v1.F0_ATLAS_EXECUTOR_SHA256,source_blob:v1.F0_SOURCES[PID],atlas_head:p1.CONFIG.atlas.head,atlas_tree:p1.CONFIG.atlas.tree}}
function claimV2(){return{schema:'kenigevents.asp-atlas-publish-claim.v1',package_id:PID,logical_writer_id:'/root/publish_r2',publish_identity:'/root/d0_publish_atlas_r2',run_id:'run-r2',lease_token:'lease-r2',cancel_token:'cancel-r2',adapter_id:v2.ADAPTER_ID,adapter_sha256:v2.ACTION_NAV_R2_EXECUTOR_SHA256,source_blob:v2.ACTION_NAV_R2_SOURCE_BLOB,atlas_head:v2.ACTION_NAV_R2_ATLAS_HEAD,atlas_tree:v2.ACTION_NAV_R2_ATLAS_TREE}}
function activate(p,claim){p.currentFile.setSharedPluginData('kenigevents','asp-active-run-v1',JSON.stringify({schema:'kenigevents.asp-run-control.v1',package_id:PID,writer_id:claim.logical_writer_id,publish_identity:claim.publish_identity,run_id:claim.run_id,lease_token:claim.lease_token,cancel_token:claim.cancel_token,adapter_id:claim.adapter_id,adapter_sha256:claim.adapter_sha256,source_blob:claim.source_blob,atlas_head:claim.atlas_head,atlas_tree:claim.atlas_tree,state:'ACTIVE',cancelled:false}))}
function padExact(shapes,target,extra){const first=shapes[0];first.name='é'.repeat(extra);let raw=canon(shapes.map(p2.exactShape)),add=target.chars-raw.length;a.ok(add>=0);first.name+='x'.repeat(add);raw=canon(shapes.map(p2.exactShape));a.equal(raw.length,target.chars);a.equal(new TextEncoder().encode(raw).length,target.utf8Bytes)}
function addDocumentationHeader(e){const page=new Pg('documentation-page-r2'),main=new S('board','documentation-header-main-r2');page.name='Documentation';main.name='Documentation / PageHeader';main.resize(2048,128);main.setSharedPluginData(CONFIG.documentation.namespace,'stable-id',CONFIG.documentation.componentStableId);main.setSharedPluginData(CONFIG.documentation.namespace,'component-id',CONFIG.documentation.componentId);for(const stable of ['atlas.header.top.section','atlas.header.top.page-title','atlas.header.top.lifecycle-status','atlas.header.meta.owner','atlas.header.meta.package-id','atlas.header.meta.source-or-fixture','atlas.header.meta.viewport-and-state-coverage','atlas.header.meta.v0-status','atlas.header.meta.last-reviewed-revision']){const x=new S('text',`header-field-${stable}`);x.setSharedPluginData(CONFIG.documentation.namespace,'stable-id',stable);main.appendChild(x)}page.root.appendChild(main);e.penpot.currentFile.pages.push(page);const c=new C(main,'documentation-component-r2');c.name='PageHeader';c.path='Documentation';e.penpot.library.local.components.push(c);return c}
function env(){id=0;const p=new P,protectedPage=new Pg('protected');protectedPage.name='Protected';protectedPage.root.appendChild(new S('board','protected-root'));p.currentFile.pages.push(protectedPage);const e={penpot:p,storage:{},claim:claimV1()};activate(p,e.claim);v1.setupF0ExistingAtlasLayoutRepairV1(e,PID);const free=new Pg(FOUNDATION.protectedPageId),fr=FOUNDATION.protectedRootIds.map(x=>new S('board',x));free.name='Free/EventCard';for(const x of fr)free.root.appendChild(x);padExact(fr,FOUNDATION.protected,1);p.currentFile.pages.push(free);const source=new Pg(FOUNDATION.sourcePageId),sourceRoot=new S('board','313fb1ed-0d5c-8095-8008-'+FOUNDATION.sourceRootSuffix);source.name='Foundations source/index';sourceRoot.setSharedPluginData(FOUNDATION.namespace,'stable-id','root');source.root.appendChild(sourceRoot);padExact([sourceRoot],FOUNDATION.source,10);p.currentFile.pages.push(source);for(const [fam,spec] of Object.entries(FOUNDATION.components)){const m=new S('board','313fb1ed-0d5c-8095-8008-'+spec.mainSuffix);m.name=`${FOUNDATION.componentPath} / ${spec.name}`;m.resize(416,128);m.setSharedPluginData(FOUNDATION.namespace,'stable-id',`component/${fam}`);source.root.appendChild(m);const c=new C(m,'313fb1ed-0d5c-8095-8008-'+spec.componentSuffix);c.name=spec.name;c.path=FOUNDATION.componentPath;p.library.local.components.push(c)}addDocumentationHeader(e);return e}
async function terminalV1(e){let out;for(let i=0;i<50;i++){out=await v1.runF0ExistingAtlasLayoutRepairV1(e,PID);if(out.terminalState==='CANDIDATE_READBACK_VERIFIED_PENDING_V0')return out}throw Error('V1_NOT_TERMINAL')}
function switchToV2(e){e.claim=claimV2();activate(e.penpot,e.claim);v2.setupActionNavAtlasR2RebindV2(e);e.penpot.created=e.penpot.pageCreates=e.penpot.boardCreates=0}
async function terminalV2(e){let out;for(let i=0;i<20;i++){out=await v2.runActionNavAtlasR2RebindV2(e);a.ok((out.created||0)<=3);if(out.terminalState==='CANDIDATE_READBACK_VERIFIED_PENDING_V0')break}a.equal(out.terminalState,'CANDIDATE_READBACK_VERIFIED_PENDING_V0');const again=await v2.runActionNavAtlasR2RebindV2(e);a.equal(again.created,0);a.equal(again.secondRunCreated,0);return out}
function target(e){const page=e.penpot.currentFile.pages.find(x=>x.getSharedPluginData('kenigevents-action-nav-r5','package-id')===PID),root=page.root.children.find(x=>x.getSharedPluginData('kenigevents-action-nav-r5','stable-id')==='root');return{page,root}}
function slot(root,id){return root.children.find(x=>x.getSharedPluginData(CONFIG.namespace,'semantic-slot')===id||x.getSharedPluginData(CONFIG.legacyNamespace,'semantic-slot')===id)}
function physicalIdentity(root){const master=slot(root,'master_column'),out=[];for(const m of master.children){const physical=m.children.length?m.children:[m];out.push(...physical.map((x,i)=>({id:x.id,content:x.content,width:x.width,height:x.height,x:i?x.x:null,y:i?x.y:null,bytes:x.getSharedPluginData('kenigevents-action-nav-r5','asset-bytes')})))}return out.sort((a,b)=>a.id.localeCompare(b.id))}

test('strict asset-bytes contract remains decimal String values',async()=>{const d=new D;a.throws(()=>d.setSharedPluginData('n','asset-bytes',374),/PLUGIN_DATA_VALUE_NOT_STRING/);const e=env();await terminalV1(e);switchToV2(e);await terminalV2(e);const values=physicalIdentity(target(e).root).map(x=>x.bytes).sort(),expected=ACTION_ASSETS.map(x=>String(x.bytes)).sort();a.deepEqual(values,expected);a.ok(values.every(x=>typeof x==='string'))});

test('discovers the R1 partial by package namespace and semantic stable IDs and rebinds in place',async()=>{const e=env();await terminalV1(e);const before=target(e),pageId=before.page.id,rootId=before.root.id,physical=physicalIdentity(before.root),pageCount=e.penpot.currentFile.pages.length;before.page.name='legacy display name is not the locator';switchToV2(e);const out=await terminalV2(e),after=target(e);a.equal(after.page.id,pageId);a.equal(after.root.id,rootId);a.deepEqual(physicalIdentity(after.root),physical);a.equal(e.penpot.currentFile.pages.length,pageCount);a.equal(e.penpot.pageCreates,0);a.equal(e.penpot.boardCreates,0);a.equal(out.counts.components,8);a.equal(out.counts.linkedInstances,18);a.equal(out.counts.detached,0);a.equal(out.counts.screenshots,0);a.deepEqual(out.validation,[])});

test('R1 to R2 rebind uses linked Documentation/PageHeader and exact deterministic DENSE geometry',async()=>{const e=env();await terminalV1(e);const {root}=target(e),oldHeader=slot(root,'header'),oldHeaderId=oldHeader.id;a.equal(oldHeader.children.some(x=>x.type==='text'),true);switchToV2(e);const out=await terminalV2(e),r=target(e).root,l=CONFIG.layout,g=l.grid,h=slot(r,'header'),master=slot(r,'master_column'),review=slot(r,'review_grid');a.equal(h.id,oldHeaderId);a.equal(h.children.length,1);a.equal(h.children[0].isComponentCopyInstance(),true);a.equal(h.children[0].component().id,'documentation-component-r2');a.equal(h.children[0].getSharedPluginData(CONFIG.documentation.namespace,'stable-id'),CONFIG.documentation.instanceStableId);a.deepEqual([r.width,r.height],[2176,944]);a.deepEqual([h.x,h.y,h.width,h.height],[64,64,2048,128]);a.deepEqual([master.x,master.y,master.width,master.height],[64,256,320,424]);a.deepEqual([review.x,review.y,review.width,review.height],[416,256,1656,624]);const instances=review.children.filter(x=>x.getSharedPluginData('kenigevents-action-nav-r5','placement-id')).sort((x,y)=>x.getSharedPluginData('kenigevents-action-nav-r5','placement-id').localeCompare(y.getSharedPluginData('kenigevents-action-nav-r5','placement-id')));a.equal(instances.length,18);instances.forEach((x,i)=>a.deepEqual([x.x,x.y],[review.x+(i%6)*(256+24)+(256-x.width)/2,review.y+Math.floor(i/6)*(192+24)+16]));a.deepEqual(out.layout,{templateId:'FOUNDATION_ASSET_GRID_DENSE_V2',columns:6,rows:3,rootWidth:2176,rootHeight:944})});

test('Free/EventCard and Foundations source/index projections stay exact through rebind and replay',async()=>{const e=env();await terminalV1(e);const free=e.penpot.currentFile.pages.find(x=>x.id===FOUNDATION.protectedPageId),source=e.penpot.currentFile.pages.find(x=>x.id===FOUNDATION.sourcePageId),before=[canon(free.root.children.map(p2.exactShape)),canon(source.root.children.map(p2.exactShape))];switchToV2(e);const out=await terminalV2(e),after=[canon(free.root.children.map(p2.exactShape)),canon(source.root.children.map(p2.exactShape))];a.deepEqual(after,before);a.deepEqual(out.protectedProjections,{free:FOUNDATION.protected.sha256,foundationSourceIndex:FOUNDATION.source.sha256});a.equal(out.penpotAuthorization,false)});

test('duplicate package page and duplicate semantic root fail before createPage/createBoard',async()=>{const e=env();await terminalV1(e);switchToV2(e);const duplicatePage=new Pg('duplicate-page');duplicatePage.name='duplicate';duplicatePage.setSharedPluginData('kenigevents-action-nav-r5','package-id',PID);e.penpot.currentFile.pages.push(duplicatePage);await a.rejects(()=>v2.runActionNavAtlasR2RebindV2(e),/DUPLICATE_OR_FOREIGN_PAGE/);a.equal(e.penpot.pageCreates,0);a.equal(e.penpot.boardCreates,0);e.penpot.currentFile.pages.pop();const {page}=target(e),r2=new S('board','duplicate-root');r2.setSharedPluginData('kenigevents-action-nav-r5','stable-id','root');page.root.appendChild(r2);await a.rejects(()=>v2.runActionNavAtlasR2RebindV2(e),/DUPLICATE_ROOT/);a.equal(e.penpot.pageCreates,0);a.equal(e.penpot.boardCreates,0)});
