import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import vm from 'node:vm';

const scriptPath='catalog/penpot-executor/g11/capsule/penpot-visual-executor.g11.js';
const expectations=JSON.parse(fs.readFileSync('catalog/penpot-executor/g11/exact-expectations.json'));
const source=fs.readFileSync(scriptPath,'utf8');
const stable=v=>JSON.stringify(v,(_k,x)=>x&&typeof x==='object'&&!Array.isArray(x)?Object.fromEntries(Object.entries(x).sort(([a],[b])=>a.localeCompare(b))):x);
const digest=v=>crypto.createHash('sha256').update(stable(v)).digest('hex');
const without=(o,keys)=>Object.fromEntries(Object.entries(o).filter(([k])=>!keys.includes(k)));
let serial=0;
class Shape{
 constructor(type,text=''){this.id=`shape-${++serial}`;this.type=type;this.characters=text;this.children=[];this.data={};this.fills=[];this.removed=false;}
 resize(w,h){this.width=w;this.height=h;} appendChild(s){if(s.parent)s.parent.children=s.parent.children.filter(x=>x!==s);s.parent=this;this.children.push(s);} setPluginData(k,v){this.data[k]=String(v);} getPluginData(k){return this.data[k]||'';} addFlexLayout(){this.layout={};return this.layout;} remove(){if(this.noRemove)throw Error('remove blocked');this.removed=true;if(this.parent)this.parent.children=this.parent.children.filter(x=>x!==this);}
}
const clone=s=>{const n=new Shape(s.type,s.characters);n.name=s.name;n.width=s.width;n.height=s.height;n.x=s.x;n.y=s.y;n.data={...s.data};n.fills=[...s.fills];for(const k of ['fontFamily','fontSize','fontWeight','lineHeight','fill','opacity','borderRadius','clipContent'])n[k]=s[k];n.children=s.children.map(c=>{const q=clone(c);q.parent=n;return q;});return n;};
function fakeSurface(){serial=0;const root=new Shape('root');const components=[];const walk=function*(s){yield s;for(const c of s.children)yield*walk(c);};const penpot={version:'fake-ordinary-1',currentPage:{root},createBoard:()=>new Shape('board'),createRectangle:()=>new Shape('rectangle'),createText:t=>new Shape('text',t),createShapeFromSvg:s=>{assert.match(s,/^<svg/);return new Shape('svg');},uploadMediaData:async(name,data)=>({id:'media-'+name,name,data:()=>data}),library:{local:{createComponent:shapes=>{const c={id:`component-${components.length+1}`,main:shapes[0],instance:()=>clone(shapes[0])};components.push(c);return c;}}}};const utils={findShape:fn=>[...walk(root)].find(fn)||null,setParentXY:(s,x,y)=>{s.x=x;s.y=y;}};return{penpot,penpotUtils:utils,root,components,walk:()=>[...walk(root)]};}
async function load(surface=fakeSurface()){const context={...surface,console,Uint8Array,Date,JSON,Math,Error,Object,Array,String,Number,Boolean,RegExp,encodeURIComponent,decodeURIComponent,escape,unescape,atob:s=>Buffer.from(s,'base64').toString('binary')};const api=await vm.runInNewContext(source,context,{filename:scriptPath});return{api,surface,context};}
function ticket(op,seq,overrides={}){const t={schema:'kenigevents.w0-penpot-mutation-ticket.v1',owner:'W3',run_id:'W3-RUN-G12-R1',generation:12,file_id:'11111111-1111-4111-8111-111111111111',page_id:'22222222-2222-4222-8222-222222222222',sequence:seq,operation:op,nonce:`ticket-${String(seq).padStart(10,'0')}-${overrides.rollback?'r':'w'}`,issued_at:'2026-08-30T20:00:00Z',expires_at:'2099-08-30T21:00:00Z',cancelled:false,...overrides};delete t.rollback;t.body_sha256=digest(t);t.w0_signature='W0:test-signature';return t;}
function authority(api,modify=()=>{}){const probe={schema:'kenigevents.penpot-native-compatibility-probe-receipt.v1',status:'COMPATIBLE',file_id:'11111111-1111-4111-8111-111111111111',page_id:'22222222-2222-4222-8222-222222222222',strategy:'clipped-native-image-shape-v1',observed:{fill_image_data_callable:true,board_clip_content:true,shape_resize:true,parent_xy:true},limitations:['bounded'],probed_at:'2026-08-30T20:05:00Z'};probe.w0_binding={key_id:'w0-test',body_sha256:digest(probe),signature:'W0:test-signature'};const tickets=api.operationPlan().map((op,i)=>ticket(op,i));const rollback_tickets=api.rollbackPlan().map((op,i)=>ticket(op,i,{rollback:true}));const capsule={schema:'kenigevents.w0-issued-w3-penpot-run-capsule.v1',owner:'W3',run_id:'W3-RUN-G12-R1',generation:12,file_id:probe.file_id,page_id:probe.page_id,issued_at:'2026-08-30T20:00:00Z',expires_at:'2099-08-30T21:00:00Z',nonce:'run-capsule-nonce-0001',cancelled:false,accepted_executor:{semantic_identity:api.identity,payload_sha256:api.payload_sha256,artifact_raw_sha256:'a'.repeat(64),commit_sha:'b'.repeat(40)},accepted_bundle:{id:'eventcard-free-slice.g4.ready-v1',content_sha256:'c'.repeat(64),authorization:'W0_ACCEPTED_FOR_W3_EXECUTION'},compatibility_probe_receipt_sha256:digest(probe),ticket_root_sha256:digest(tickets.map(t=>t.body_sha256)),tickets,rollback_ticket_root_sha256:digest(rollback_tickets.map(t=>t.body_sha256)),rollback_tickets};modify({capsule,probe,tickets,rollback_tickets});capsule.ticket_root_sha256=digest(capsule.tickets.map(t=>t.body_sha256));capsule.rollback_ticket_root_sha256=digest(capsule.rollback_tickets.map(t=>t.body_sha256));capsule.w0_binding={key_id:'w0-test',body_sha256:digest(without(capsule,['tickets','w0_binding'])),signature:'W0:test-signature'};return{capsule,probeReceipt:probe};}

const byKey=(surface,key)=>surface.walk().find(s=>s.getPluginData?.('kenigevents-semantic-key')===key);

test('artifact is run-agnostic and forbidden-surface clean',async()=>{assert.doesNotMatch(source,/generation\s*[:=]\s*1[01]|owner\s*[:=]\s*['"]W2|w2-penpot-visual-executor-g1[01]/);for(const p of [/\brequire\s*\(/,/node:/,/\bprocess\b/,/\bfetch\s*\(/,/XMLHttpRequest/,/github\.com/i,/node:fs/,/node:path/,/node:crypto/])assert.doesNotMatch(source,p);const{api}=await load();assert.equal(api.identity,'kenigevents.free-collection.ordinary-penpot-visual-executor');assert.match(api.threat_model.limitation,/cannot observe a cancellation/);});

test('independent expectations preserve exact occurrence, place, title, grids and equal height',()=>{const c=expectations.cases.find(x=>x.fixture_id==='event.real.8006'&&x.variant.startsWith('desktop'));assert.equal(c.content.occurrence,'2 сентября 09:00');assert.equal(c.content.place,'Гурьевск · Центр культуры и досуга');assert.deepEqual(c.typography.title,{fontFamily:'Inter',fontSize:21.6,fontWeight:900,lineHeight:1.08,fill:'#ffffff'});assert.deepEqual(expectations.groups.map(g=>g.gap),[16,20,16,16]);assert.equal(expectations.groups[0].equal_height,true);assert.equal(expectations.groups[1].equal_height,true);assert.equal(expectations.component_model.master_count,1);});

test('W3 capsule, compatibility probe, and ticket validation fail closed before writes',async()=>{const{api,surface}=await load();await assert.rejects(api.execute({}),/RUN_CAPSULE_MISSING/);assert.equal(surface.root.children.length,0);const bad=authority(api,({capsule})=>capsule.owner='W2');await assert.rejects(api.execute(bad),/RUN_OWNER_NOT_W3/);assert.equal(surface.root.children.length,0);const missingProbe=authority(api);delete missingProbe.probeReceipt;await assert.rejects(api.execute(missingProbe),/COMPATIBILITY_PROBE_REQUIRED/);assert.equal(surface.root.children.length,0);});

test('faithful ordinary-Penpot run creates exact L0-L3 hierarchy and one linked master',async()=>{const{api,surface}=await load();const receipt=await api.execute(authority(api));assert.equal(receipt.terminal_state,'SUCCEEDED');for(const key of ['g11.L0','g11.L1','g11.L2','g11.L3','asset.nav-afisha','media.event.real.8006','leaf.event-type','leaf.medallion','case.eventcard.desktop-wide-calendar.8006','group.row.desktop.events','group.row.desktop.exhibitions','group.group.mobile.events','group.group.mobile.exhibitions'])assert.ok(byKey(surface,key),key);assert.equal(surface.components.length,1);assert.equal(receipt.component_lineage.filter(x=>x.master_id).length,1);assert.ok(receipt.component_lineage.filter(x=>x.instance_id).every(x=>x.linked));const card=byKey(surface,'case.eventcard.desktop-wide-calendar.8006');assert.equal(card.width,531);assert.equal(card.height,870.515625);const title=card.children.find(x=>x.name==='title');assert.equal(title.characters,'Донорская акция «Стань донором крови»');assert.equal(title.fontSize,21.6);const occurrence=card.children.find(x=>x.name==='occurrence');assert.equal(occurrence.characters,'2 сентября 09:00');const place=card.children.find(x=>x.name==='place');assert.equal(place.characters,'Гурьевск · Центр культуры и досуга');assert.equal(card.getPluginData('kenigevents-actions'),'share,like,not_interested,calendar');const packed=byKey(surface,'case.eventcard.desktop-packed-calendar-absent.2182');assert.equal(packed.getPluginData('kenigevents-actions'),'share,like,not_interested');const row=byKey(surface,'group.row.desktop.events');assert.equal(row.layout.gap,16);assert.equal(row.getPluginData('kenigevents-equal-height'),'true');assert.equal(receipt.pre_write_checks.length,receipt.completed_mutations.length);assert.ok(receipt.pre_write_checks.every(x=>x.checked_immediately_before_write));});

test('second run is idempotent with no duplicate roots/components',async()=>{const{api,surface}=await load();await api.execute(authority(api));const before=surface.walk().length;const second=await api.execute(authority(api));assert.equal(second.terminal_state,'SUCCEEDED_IDEMPOTENT_REUSE');assert.equal(second.created.length,0);assert.equal(surface.walk().length,before);assert.equal(surface.components.length,1);});

test('cancel, stale generation, expiry, and replay are rejected between writes with rollback',async()=>{for(const mode of ['cancel','stale','expiry','replay']){const{api,surface}=await load();const auth=authority(api,({tickets})=>{const i=12;if(mode==='cancel')tickets[i].cancelled=true;if(mode==='stale')tickets[i].generation=11;if(mode==='expiry')tickets[i].expires_at='2020-01-01T00:00:00Z';if(mode==='replay')tickets[i].nonce=tickets[i-1].nonce;for(const j of [i]){const t=tickets[j];delete t.body_sha256;delete t.w0_signature;t.body_sha256=digest(t);t.w0_signature='W0:test-signature';}});let err;try{await api.execute(auth);}catch(e){err=e;}assert.ok(err,mode);assert.match(err.code,/CANCELLED|BINDING_MISMATCH|EXPIRED|REPLAY/);assert.equal(err.receipt.terminal_state,'FAILED_ROLLED_BACK');assert.equal(surface.root.children.length,0);}});

test('incomplete rollback emits exact FAILED_PARTIAL_STATE receipt',async()=>{const{api,surface}=await load();const auth=authority(api,({tickets,rollback_tickets})=>{tickets[14].cancelled=true;delete tickets[14].body_sha256;delete tickets[14].w0_signature;tickets[14].body_sha256=digest(tickets[14]);tickets[14].w0_signature='W0:test';rollback_tickets.length=0;});let err;try{await api.execute(auth);}catch(e){err=e;}assert.equal(err.receipt.terminal_state,'FAILED_PARTIAL_STATE');assert.ok(err.receipt.completed_mutations.length>0);assert.ok(err.receipt.unreverted_mutations.length>0);assert.ok(surface.root.children.length>0);});

test('expectations are independent from generator and reject substitute formulas',()=>{const generator=fs.readFileSync('scripts/round-trip-reconstruction/generate-penpot-visual-executor-g11.mjs','utf8');assert.doesNotMatch(generator,/width_formula|height_formula|Math\.max\(contract|viewport\.width\s*-/);assert.equal(expectations.status,'EXECUTOR_EVIDENCE_BINDING_NOT_CANONICAL_AUTHORITY');assert.ok(expectations.cases.every(c=>c.trace.resolved_case&&c.trace.geometry_evidence&&c.trace.astro_component));});
