'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const M=require('../../../../scripts/asp-production-conveyor-v3/mat/eventcard-media-binding-r2/eventcard_media_projection_binding_r2.js');
class Adapter{
 constructor(){this.rev=178;this.m='';this.token='stable';this.parentCalls=0;this.rows=new Map();for(const[n,s]of M.CASES.entries()){const f=M.FACTS[s.fixtureId];this.rows.set(s.rootId,{id:'media-'+n,parentId:'parent-'+n,slot:M.SLOT,local:{x:n,y:n},parent:{x:100+n,y:200+n},bounds:{x:100+n,y:200+n,width:390,height:520},fills:[{fillOpacity:1,fillImage:'image-'+n}],imageData:{id:'image-'+n,sha:f.sha,bytes:f.bytes},transform:{a:1,b:0,c:0,d:1,e:0,f:0},rotation:0,flipX:false,flipY:false,fit:f.fit,focal:f.focal,source:{path:f.path,sha:f.sha,bytes:f.bytes,w:f.w,h:f.h}})}}
 identity(){return{fileId:M.FILE_ID,pageId:M.PAGE_ID,revision:this.rev}}
 collection(){return{rootId:M.COLLECTION_ID,children:18,components:18,validation:[],protected:{token:this.token}}}
 media(root){return[this.rows.get(root)]} read(v){return v} marker(){return this.m} writeMarker(_,v){this.m=v}
 async exclusive(f){return f()}
 coverage(id){const x=[...this.rows.values()].find(y=>y.id===id);return{status:'KNOWN_PASS',uncovered:0,overlays:0,sha:x.imageData.sha}}
}
const auth=p=>({schema:'media-binding-auth-r2',packageId:M.PACKAGE_ID,parentPackageId:M.PARENT_PACKAGE_ID,state:'ACTIVE',authorized:true,cancelled:false,revision:p.revision,projectionSha256:p.projectionSha256,parentAuthorization:{package_id:M.PARENT_PACKAGE_ID}});
test('mutation-free projection binds four complete current rows',()=>{const a=new Adapter(),p=M.projectEventcardMediaBindingR2(a);assert.equal(p.revision,178);assert.equal(p.rows.length,4);assert.equal(new Set(p.rows.map(x=>x.rootId)).size,4);assert.equal(new Set(p.rows.map(x=>x.currentMediaShapeId)).size,4);assert.equal(new Set(p.rows.map(x=>x.currentParentOrGroupId)).size,4);for(const r of p.rows){assert.ok(r.bounds.width>0&&r.bounds.height>0);assert.ok(r.fills.length);assert.equal(r.imageDataIdentity.sha,r.exactSourceImageIdentity.sha);assert.equal(r.imageDataIdentity.bytes,r.exactSourceImageIdentity.bytes);assert.equal(r.focalPoint,'50% 50%');assert.equal(typeof r.horizontalFlip,'boolean');assert.equal(typeof r.verticalFlip,'boolean')}assert.equal(p.penpotMutations,0);assert.equal(p.projectionSha256,M.projectEventcardMediaBindingR2(a).projectionSha256)});
test('authorization binds current revision and projection SHA before one parent call',async()=>{const a=new Adapter(),p=M.projectEventcardMediaBindingR2(a);let calls=0;const r=await M.executeEventcardMediaProjectionBindingR2(a,auth(p),async()=>{calls++;return{acceptedRootMutations:4}});assert.equal(calls,1);assert.equal(r.boundRows.length,4);assert.equal(M.readDistinctLaterMediaBindingR2(a,r).rows,4);await assert.rejects(()=>M.executeEventcardMediaProjectionBindingR2(a,auth(p),async()=>{}),e=>e.code==='MEDIA_EXECUTOR_REPLAY_FORBIDDEN')});
test('stale revision, source, imageData and duplicate current IDs fail closed',async()=>{let a=new Adapter(),p=M.projectEventcardMediaBindingR2(a);a.rev++;await assert.rejects(()=>M.executeEventcardMediaProjectionBindingR2(a,auth(p),async()=>{}),e=>e.code==='MEDIA_STALE_REVISION');a=new Adapter();a.rows.get(M.CASES[0].rootId).source.sha='bad';assert.throws(()=>M.projectEventcardMediaBindingR2(a),e=>e.code==='MEDIA_SOURCE_OR_SEMANTICS_DRIFT');a=new Adapter();a.rows.get(M.CASES[0].rootId).imageData.sha='bad';assert.throws(()=>M.projectEventcardMediaBindingR2(a),e=>e.code==='MEDIA_IMAGEDATA_IDENTITY_DRIFT');a=new Adapter();a.rows.get(M.CASES[1].rootId).id=a.rows.get(M.CASES[0].rootId).id;assert.throws(()=>M.projectEventcardMediaBindingR2(a),e=>e.code==='MEDIA_IDS_NOT_UNIQUE')});
test('strict plugin strings',()=>{assert.throws(()=>M.str(374),e=>e.code==='MEDIA_PLUGIN_DATA_NOT_STRING');assert.equal(M.str('374'),'374')});
