'use strict';
const FOUNDATION_REVIEW_R2_PAYLOAD=Object.freeze({
  path:'scripts/asp-production-conveyor-v3/d0/mat/foundation_review_atlas_r2_relayout_payload_v2.js',
  bytes:45516,
  sha256:'e7712f21a0274f8bd35e0acbeb002fcf378a76682c44072e6ebc6d3da5a94221',
  gitBlobSha1:'2414fd90b0897dd269c675b6dfcd80c4b1ec22cb'
});
const ATLAS_R2=Object.freeze({branch:'o0/penpot-atlas-layout-v2-20260901',head:'663be702d481972cb2e8863af500f1c35dda1d8c',tree:'cf9a1e6a5e0a84aea5636334dbd3be4961039b75',bindingsBlob:'23475806beebfbe21bd77759440c169c60627550',templateId:'FOUNDATION_ASSET_GRID_STANDARD_V2'});
const SOURCE=Object.freeze({branch:'agent/f0-foundation-page-split-r1',head:'45499cc610a1bb5cbf36b8531c65b036d731013f',tree:'6ed4fca2d754c3270b066f536bd82a0492c64755',path:'scripts/asp-production-conveyor-v3/f0/foundation_review_pages_native_adapter_v1.js',blob:'3d81ace5033b4ccde60291340c8019eb8ee3ba49',bytes:17146,sha256:'68d9d6a7ffd49855b3092af6ebfced0d2e0f55de621ff16358903d326ceebe89'});
const FILE_ID='40e06342-8830-80d6-8008-8fc8a3a4cd4f';
const EXECUTION_TUPLES=Object.freeze({
  'F-FOUNDATIONS-REVIEW-COLORS-STATUS':Object.freeze({executionTupleId:'F-FOUNDATIONS-REVIEW-COLORS-STATUS',adapterId:'D0-MAT-F-FOUNDATIONS-REVIEW-COLORS-STATUS-ATLAS-R2',atlasPageId:'foundations-review-colors-status',pageOrder:'0050',pageName:'03.1 · Foundations · Colors & status · Candidate',families:Object.freeze(['foundation.colors-and-modes','foundation.status']),instances:26,source:SOURCE,atlas:ATLAS_R2,payload:FOUNDATION_REVIEW_R2_PAYLOAD}),
  'F-FOUNDATIONS-REVIEW-SPACING-SIZING':Object.freeze({executionTupleId:'F-FOUNDATIONS-REVIEW-SPACING-SIZING',adapterId:'D0-MAT-F-FOUNDATIONS-REVIEW-SPACING-SIZING-ATLAS-R2',atlasPageId:'foundations-review-spacing-sizing',pageOrder:'0060',pageName:'03.2 · Foundations · Spacing & sizing · Candidate',families:Object.freeze(['foundation.spacing','foundation.sizing-density']),instances:14,source:SOURCE,atlas:ATLAS_R2,payload:FOUNDATION_REVIEW_R2_PAYLOAD}),
  'F-FOUNDATIONS-REVIEW-SHAPE-ELEVATION':Object.freeze({executionTupleId:'F-FOUNDATIONS-REVIEW-SHAPE-ELEVATION',adapterId:'D0-MAT-F-FOUNDATIONS-REVIEW-SHAPE-ELEVATION-ATLAS-R2',atlasPageId:'foundations-review-shape-elevation',pageOrder:'0070',pageName:'03.3 · Foundations · Shape, borders & elevation · Candidate',families:Object.freeze(['foundation.radius-border','foundation.elevation']),instances:8,source:SOURCE,atlas:ATLAS_R2,payload:FOUNDATION_REVIEW_R2_PAYLOAD}),
  'F-FOUNDATIONS-REVIEW-MOTION-ACCESSIBILITY':Object.freeze({executionTupleId:'F-FOUNDATIONS-REVIEW-MOTION-ACCESSIBILITY',adapterId:'D0-MAT-F-FOUNDATIONS-REVIEW-MOTION-ACCESSIBILITY-ATLAS-R2',atlasPageId:'foundations-review-motion-accessibility',pageOrder:'0080',pageName:'03.4 · Foundations · Motion & accessibility · Candidate',families:Object.freeze(['foundation.motion','foundation.accessibility']),instances:9,source:SOURCE,atlas:ATLAS_R2,payload:FOUNDATION_REVIEW_R2_PAYLOAD})
});
const req=(ok,message)=>{if(!ok)throw Error(message)};
function checkFoundationReviewAtlasR2Claim(penpot,claim,packageId){const tuple=EXECUTION_TUPLES[packageId];req(tuple,'UNCLASSIFIED_PACKAGE');req(penpot.currentFile?.id===FILE_ID,'WRONG_FILE');req(claim?.schema==='kenigevents.asp-atlas-publish-claim.v1'&&claim.package_id===packageId&&claim.logical_writer_id==='/root/publish_r2'&&claim.adapter_id===tuple.adapterId&&claim.adapter_sha256===tuple.payload.sha256&&claim.source_blob===tuple.source.blob&&claim.atlas_head===tuple.atlas.head&&claim.atlas_tree===tuple.atlas.tree&&typeof claim.publish_identity==='string'&&claim.publish_identity&&typeof claim.run_id==='string'&&claim.run_id&&typeof claim.lease_token==='string'&&claim.lease_token&&typeof claim.cancel_token==='string'&&claim.cancel_token,'PUBLISH_CLAIM_INVALID');let run;try{run=JSON.parse(penpot.currentFile.getSharedPluginData('kenigevents','asp-active-run-v1')||'null')}catch{throw Error('ACTIVE_RUN_INVALID')}req(run?.schema==='kenigevents.asp-run-control.v1'&&run.package_id===packageId&&run.writer_id===claim.logical_writer_id&&run.publish_identity===claim.publish_identity&&run.run_id===claim.run_id&&run.lease_token===claim.lease_token&&run.cancel_token===claim.cancel_token&&run.adapter_id===claim.adapter_id&&run.adapter_sha256===tuple.payload.sha256&&run.source_blob===tuple.source.blob&&run.atlas_head===tuple.atlas.head&&run.atlas_tree===tuple.atlas.tree&&run.state==='ACTIVE'&&!run.cancelled,'CANCELLED_OR_INACTIVE_LEASE');return tuple}
function setupFoundationReviewAtlasR2RelayoutV2({penpot,storage,claim},packageId){const tuple=checkFoundationReviewAtlasR2Claim(penpot,claim,packageId),binding=Object.freeze({schema:'kenigevents.asp-foundation-review-atlas-binding.v2',execution_tuple_id:tuple.executionTupleId,adapter_id:tuple.adapterId,adapter_sha256:tuple.payload.sha256,adapter_git_blob_sha1:tuple.payload.gitBlobSha1,source_head:tuple.source.head,source_blob:tuple.source.blob,atlas_head:tuple.atlas.head,atlas_tree:tuple.atlas.tree,atlas_bindings_blob:tuple.atlas.bindingsBlob,template_id:tuple.atlas.templateId,package_id:packageId,publish_identity:claim.publish_identity,logical_writer_id:claim.logical_writer_id,run_id:claim.run_id,lease_token:claim.lease_token,cancel_token:claim.cancel_token});storage[`d0F0FoundationReviewAtlasBindingV2:${packageId}`]=binding;return{schema:'kenigevents.asp-foundation-review-atlas-setup-result.v2',state:'ACTIVE',mutations:0,penpotAuthorization:false,binding}}
let payloadRun=null;if(typeof module!=='undefined'&&module.exports)payloadRun=require('./foundation_review_atlas_r2_relayout_payload_v2.js').runFoundationReviewAtlasR2RelayoutPayloadV2;
async function runFoundationReviewAtlasR2RelayoutV2(ctx,packageId){const tuple=checkFoundationReviewAtlasR2Claim(ctx.penpot,ctx.claim,packageId),run=payloadRun||globalThis.runFoundationReviewAtlasR2RelayoutPayloadV2;req(typeof run==='function','PAYLOAD_NOT_LOADED');return await run(ctx,packageId,tuple.payload.sha256)}
if(typeof module!=='undefined'&&module.exports)module.exports={FOUNDATION_REVIEW_R2_PAYLOAD,ATLAS_R2,SOURCE,EXECUTION_TUPLES,checkFoundationReviewAtlasR2Claim,setupFoundationReviewAtlasR2RelayoutV2,runFoundationReviewAtlasR2RelayoutV2};
