import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { SPEC, PACKAGE, EXECUTION_TUPLE, DECLARED_CHECKOUT } from './data.v1.mjs';
import { execute } from './executor.v1.mjs';
import { NativeLikeDocument, buildFixtureContext } from './native-like-host.v1.mjs';
import { renderGeneratedManifest } from './regenerate.v1.mjs';

const CYRILLIC=/[А-Яа-яЁё]/;

test('exact package, parent, Atlas R2 and gated state',()=>{assert.equal(PACKAGE.package_id,SPEC.package_id);assert.equal(EXECUTION_TUPLE.package_id,SPEC.package_id);assert.equal(PACKAGE.state,'MAT_PACKAGE_READY_QA_INTEGRATE_GATED');assert.equal(SPEC.atlas.commit,'663be702d481972cb2e8863af500f1c35dda1d8c');assert.equal(SPEC.atlas.tree,'cf9a1e6a5e0a84aea5636334dbd3be4961039b75');assert.equal(SPEC.page.width,2176);assert.equal(EXECUTION_TUPLE.force,false);assert.equal(EXECUTION_TUPLE.penpot_reads,0);assert.equal(EXECUTION_TUPLE.penpot_mutations,0);});

test('deterministic exact Atlas page binding and linked header contract',()=>{assert.equal(SPEC.page.id,'medallions-institutions-a');assert.equal(SPEC.page.name,'04.1 · Assets · Medallions · Institutions A · Candidate');assert.equal(SPEC.page.height,SPEC.page.height_formula_result);assert.equal(SPEC.page.root_bounds[2],2176);assert.equal(SPEC.atlas.header_component_id,'ATLAS_PAGE_HEADER_V2');assert.equal(SPEC.page.template_id,'FOUNDATION_ASSET_GRID_DENSE_V2');assert.deepEqual(SPEC.page.semantic_slots,{header:'page_header',master_column:'package_owned_masters',review_grid:'linked_review_instances'});});

test('first native-like run creates concrete non-metadata surface',async()=>{const ctx=buildFixtureContext();const result=await execute(ctx);assert.equal(result.created,EXECUTION_TUPLE.replay.first_run_created);assert.equal(result.validation.detached,0);assert.equal(result.validation.screenshots,0);assert.equal(result.validation.empty_specimen_wells,0);assert.equal(result.validation.metadata_only_surfaces,0);assert.equal(result.validation.placeholder_only_surfaces,0);assert.equal(ctx.document.countRole('atlas-header-instance'),1);assert.equal(ctx.document.countRole('candidate-root'),1);assert.equal(ctx.document.countRole('linked-specimen'),SPEC.expected.linked_specimens);});

test('actual second replay creates zero and preserves all native nodes',async()=>{const ctx=buildFixtureContext();const first=await execute(ctx);const before=ctx.document.snapshot();const second=await execute(ctx);const after=ctx.document.snapshot();assert.ok(first.created>0);assert.equal(second.created,0);assert.equal(second.second_run_created,0);assert.equal(before,after);assert.deepEqual(first.protected_before,first.protected_after);assert.deepEqual(second.protected_before,second.protected_after);});

test('strict shared-plugin-data double rejects implicit coercion',async()=>{const document=new NativeLikeDocument();const page=document.ensurePage('negative.page',{name:'negative'});assert.throws(()=>document.setSharedPluginData(page,'negative','value',7),/must be string/);const ctx=buildFixtureContext();await execute(ctx);for(const value of ctx.document.pluginData.values())assert.equal(typeof value,'string');});

test('protected Free/EventCard and Foundations source/index remain unchanged',async()=>{const ctx=buildFixtureContext();const expected={...ctx.document.projections};await execute(ctx);assert.deepEqual(ctx.document.projections,expected);for(const item of Object.values(SPEC.protected_projections))assert.equal(ctx.document.projectionDigest(item.projection_id),item.sha256);});

test('package-specific native source-bound gates',async()=>{const ctx=buildFixtureContext();const result=await execute(ctx);if(SPEC.kind==='medallions'){assert.equal(SPEC.package_id,'F-MEDALLIONS-INSTITUTIONS-A-R2-NATIVE');assert.equal(DECLARED_CHECKOUT.assets.length,8);assert.equal(DECLARED_CHECKOUT.external_manifest_required,false);assert.equal(DECLARED_CHECKOUT.missing_donor_manifest_dependency,false);assert.equal(SPEC.assets.length,8);assert.equal(new Set(SPEC.assets.map((item)=>item.source.sha256)).size,8);assert.ok(SPEC.assets.every((item)=>item.consumer_group==='institutions-a'&&item.tiers_px.join('/')==='44/60/88'));assert.equal(result.asset_masters,8);assert.equal(result.source_artworks,8);assert.equal(result.master_surfaces,8);assert.equal(result.master_previews,0);assert.equal(result.linked_specimens,24);assert.equal(ctx.document.countRole('master-preview'),0);assert.equal(result.placeholder_cells,0);assert.equal(result.empty_asset_wells,0);assert.equal(result.generic_circles,0);}else if(SPEC.kind==='foundation'){assert.equal(SPEC.page.template_family,'STANDARD_V2');assert.equal(result.product_components_reused,SPEC.families.length);assert.equal(result.new_foundation_families,0);assert.equal(ctx.document.countRole('specimen-visual'),SPEC.placements.length);assert.equal(ctx.document.countRole('specimen-label'),SPEC.placements.length);}else{assert.equal(SPEC.page.template_family,'WIDE');assert.equal(SPEC.font_binding.semantic_css_family.startsWith('Inter,'),true);assert.equal(SPEC.font_binding.resolved_family,'DejaVu Sans');assert.equal(SPEC.font_binding.regular.bytes,759720);assert.equal(SPEC.font_binding.bold.bytes,708920);assert.ok(Object.values(SPEC.line_heights).every((value)=>Number.isFinite(value)&&value>0.5&&value<2.5));assert.ok(SPEC.placements.every((item)=>CYRILLIC.test(item.text)));assert.deepEqual(result.responsive_roles,['desktop','tablet','mobile']);assert.equal(result.editable_cyrillic_text_nodes,SPEC.placements.length*3);assert.equal(result.empty_specimen_wells,0);assert.equal(result.does_not_repair_eventcard_text,true);assert.equal(SPEC.does_not_repair_eventcard_text,true);}});

test('deterministic regeneration exactly matches committed manifest',()=>{const committed=fs.readFileSync(new URL('./generated.manifest.v1.json',import.meta.url),'utf8');assert.equal(renderGeneratedManifest(),committed);assert.equal(renderGeneratedManifest(),renderGeneratedManifest());});
