import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { SPEC, PACKAGE, EXECUTION_TUPLE } from './data.v1.mjs';
import { execute } from './executor.v1.mjs';

function canonical(v){ if(Array.isArray(v))return`[${v.map(canonical).join(',')}]`; if(v&&typeof v==='object')return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`; return JSON.stringify(v); }
function digest(v){return crypto.createHash('sha256').update(canonical(v)).digest('hex');}
class NativeDocument{
  constructor(){this.kind='native-like-document-v1';this.nodes=new Map();this.pluginData=new Map();this.currentCreated=0;this.activePackageId=null;this.protected=Object.freeze({atlas_commit:SPEC.atlas.commit,atlas_tree:SPEC.atlas.tree,paths:['reports/asp-production-conveyor-v3/atlas-v2/','penpot/'],sentinel:'PROTECTED_PROJECTIONS_UNCHANGED'});}
  beginRun(id){assert.equal(this.activePackageId,null);this.activePackageId=id;this.currentCreated=0;} endRun(){const n=this.currentCreated;this.activePackageId=null;return n;} protectedDigest(){return digest(this.protected);}
  ensureNode(id,type,parentId,props){const e=this.nodes.get(id);if(e){assert.equal(e.type,type);assert.equal(e.parentId,parentId||null);assert.equal(canonical(e.props),canonical(props),`${id}: props drift`);return e;}if(parentId)assert.ok(this.nodes.has(parentId),`${id}: missing parent ${parentId}`);const n={id,type,parentId:parentId||null,props:structuredClone(props),children:[],...props};this.nodes.set(id,n);if(parentId)this.nodes.get(parentId).children.push(id);this.currentCreated++;return n;}
  ensurePage(i,p){return this.ensureNode(i,'page',null,p)} ensureBoard(i,q,p){return this.ensureNode(i,'board',q,p)} ensureGrid(i,q,p){return this.ensureNode(i,'grid',q,p)} ensureFlex(i,q,p){return this.ensureNode(i,'flex',q,p)} ensureComponentMaster(i,p){return this.ensureNode(i,'component-master',null,p)} ensureText(i,q,p){return this.ensureNode(i,'text',q,p)} ensureArtwork(i,q,p){return this.ensureNode(i,'artwork',q,p)}
  ensureLinkedInstance(i,q,c,p){assert.ok(this.nodes.has(c),`${i}: missing component ${c}`);return this.ensureNode(i,'instance',q,{...p,componentId:c,linked:true});}
  setSharedPluginData(n,ns,k,v){assert.equal(typeof v,'string',`non-string plugin data rejected: ${ns}:${k}`);const id=`${n.id}|${ns}|${k}`;if(this.pluginData.has(id))assert.equal(this.pluginData.get(id),v);this.pluginData.set(id,v);}
  countRole(r,p){return[...this.nodes.values()].filter(n=>n.role===r&&n.ownerPackageId===p).length;} byRole(r,p=SPEC.package_id){return[...this.nodes.values()].filter(n=>n.role===r&&n.ownerPackageId===p);}
  countDetachedInstances(p){return[...this.nodes.values()].filter(n=>n.type==='instance'&&n.ownerPackageId===p&&(!n.linked||!n.componentId||!this.nodes.has(n.componentId))).length;} countScreenshots(p){return[...this.nodes.values()].filter(n=>n.ownerPackageId===p&&(n.type==='image'||n.screenshot===true)).length;}
}

test('immutable package and frozen execution tuple are exact',()=>{assert.equal(PACKAGE.package_id,SPEC.package_id);assert.equal(PACKAGE.directive_id,SPEC.directive_id);assert.equal(PACKAGE.state,'MAT_PACKAGE_READY_QA_INTEGRATE_GATED');assert.equal(SPEC.atlas.commit,'663be702d481972cb2e8863af500f1c35dda1d8c');assert.equal(SPEC.page.width,2176);assert.equal(SPEC.atlas.header_component_id,'ATLAS_PAGE_HEADER_V2');assert.equal(EXECUTION_TUPLE.source_head,PACKAGE.source.head);assert.equal(EXECUTION_TUPLE.target_branch,PACKAGE.branch);assert.equal(EXECUTION_TUPLE.penpot_reads,0);assert.equal(EXECUTION_TUPLE.penpot_mutations,0);assert.equal(EXECUTION_TUPLE.protected_projections_unchanged,true);});
test('first native-like run creates concrete linked Atlas page',()=>{const d=new NativeDocument(),r=execute(d);assert.equal(r.state,'MAT_PACKAGE_READY_QA_INTEGRATE_GATED');assert.ok(r.created>0);assert.equal(r.detached,0);assert.equal(r.screenshots,0);assert.equal(r.page_width,2176);assert.equal(d.countRole('atlas-header-instance',SPEC.package_id),1);assert.equal(d.byRole('candidate-root').length,1);assert.equal(d.byRole('linked-specimen').length,SPEC.expected.linked_specimens);});
test('second replay is idempotent and protected projections stay unchanged',()=>{const d=new NativeDocument(),a=execute(d),before=digest([...d.nodes.values()]),b=execute(d),after=digest([...d.nodes.values()]);assert.ok(a.created>0);assert.equal(b.created,0);assert.equal(b.detached,0);assert.equal(b.screenshots,0);assert.equal(a.protected_before,a.protected_after);assert.equal(b.protected_before,b.protected_after);assert.equal(before,after);assert.equal(EXECUTION_TUPLE.replay.first_run_created,a.created);assert.equal(EXECUTION_TUPLE.replay.second_run_created,0);});
test('strict plugin-data double rejects non-string values',()=>{const d=new NativeDocument(),p=d.ensurePage('negative.page',{name:'negative',ownerPackageId:SPEC.package_id});assert.throws(()=>d.setSharedPluginData(p,'negative','value',7),/non-string plugin data rejected/);execute(d);for(const value of d.pluginData.values())assert.equal(typeof value,'string');});
test('package-specific source-bound gates pass',()=>{const d=new NativeDocument(),r=execute(d);if(SPEC.kind==='foundation'){assert.equal(SPEC.page.template_family,'STANDARD_V2');assert.equal(r.product_component_masters,SPEC.families.length);assert.equal(r.linked_specimens,SPEC.placements.length);assert.equal(r.grid_shells,1);assert.equal(r.flex_sections,SPEC.families.length);assert.deepEqual(d.byRole('product-component-master').map(n=>n.stableFamilyId).sort(),SPEC.families.map(f=>f.id).sort());}else if(SPEC.kind==='medallions'){assert.equal(SPEC.source_authority.inference_forbidden,true);assert.equal(SPEC.assets.length,8);assert.equal(new Set(SPEC.assets.map(a=>a.semantic_id)).size,8);assert.equal(new Set(SPEC.assets.map(a=>a.source.sha256)).size,8);assert.ok(SPEC.assets.every(a=>a.tiers_px.join('/')==='44/60/88'));assert.equal(r.asset_masters,8);assert.equal(r.master_previews,8);assert.equal(r.linked_specimens,24);assert.equal(d.byRole('source-artwork').length,8);assert.equal(r.placeholder_cells,0);assert.equal(r.empty_asset_wells,0);}else{assert.equal(SPEC.page.template_family,'WIDE');assert.equal(SPEC.font_binding.regular.family,'DejaVu Sans');assert.equal(SPEC.font_binding.bold.family,'DejaVu Sans');assert.ok(SPEC.placements.every(p=>/[А-Яа-яЁё]/.test(p.text)));assert.ok(Object.values(SPEC.line_heights).every(v=>Number.isFinite(v)&&v>0.5&&v<2.5));assert.ok(d.byRole('editable-cyrillic-specimen').every(n=>n.editable===true));assert.equal(r.linked_specimens,SPEC.placements.length);assert.equal(r.editable_cyrillic_specimens,SPEC.placements.length);assert.equal(r.does_not_repair_eventcard_text,true);assert.equal(SPEC.does_not_repair_eventcard_text,true);}});
