'use strict';
const crypto=require('node:crypto'),assert=require('node:assert/strict');
const PACKAGE_ID='MAT-EVENTCARD-TEXT-R11C-EXECUTION-BINDING-R2',PARENT_PACKAGE_ID='MAT-EVENTCARD-TEXT-R11C-COMPATIBLE-REPAIR';
const FILE_ID='40e06342-8830-80d6-8008-8fc8a3a4cd4f',PAGE_ID='c16498cb-b51d-8030-8008-904bd8fc9c53',COLLECTION_ID='313fb1ed-0d5c-8095-8008-9108df52b2ce';
const TARGETS=[
['eventcard.desktop-wide-calendar.8006','313fb1ed-0d5c-8095-8008-912c45090653','313fb1ed-0d5c-8095-8008-912c46b9ecba','2 сентября 09:00'],
['eventcard.desktop-packed-calendar-absent.2182','313fb1ed-0d5c-8095-8008-914c76615924','313fb1ed-0d5c-8095-8008-914c77b9c576','11 января 14:00'],
['eventcard.mobile-wide-calendar.8006','313fb1ed-0d5c-8095-8008-916b340de148','313fb1ed-0d5c-8095-8008-916b3552cb12','2 сентября 09:00'],
['eventcard.mobile-packed-calendar-absent.2182','313fb1ed-0d5c-8095-8008-916bd0ab6c98','313fb1ed-0d5c-8095-8008-916bd1ff0eb3','11 января 14:00']
].map(([caseId,rootId,id,characters])=>({caseId,rootId,id,characters}));
const PROTECTED=['313fb1ed-0d5c-8095-8008-912d41586b13','313fb1ed-0d5c-8095-8008-912d4fa0afe5','313fb1ed-0d5c-8095-8008-912d500a695a','313fb1ed-0d5c-8095-8008-912d506e9dba','313fb1ed-0d5c-8095-8008-914c77dfcf31','313fb1ed-0d5c-8095-8008-916afac06e71','313fb1ed-0d5c-8095-8008-916b0aa7e2a6','313fb1ed-0d5c-8095-8008-916b0af29b13','313fb1ed-0d5c-8095-8008-916b376e6f1c','313fb1ed-0d5c-8095-8008-916baef0312c','313fb1ed-0d5c-8095-8008-916baf75cc83','313fb1ed-0d5c-8095-8008-916bafe5eea9','313fb1ed-0d5c-8095-8008-916bd231c7cd','313fb1ed-0d5c-8095-8008-916bd4d215df','313fb1ed-0d5c-8095-8008-916be6eddba1','313fb1ed-0d5c-8095-8008-916be7436f37'];
class Stop extends Error{constructor(code,unknown=false){super(code);this.code=code;this.unknownOutcome=unknown;this.retryAllowed=false}}
const fail=(c,u=false)=>{throw new Stop(c,u)},canon=v=>Array.isArray(v)?`[${v.map(canon)}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canon(v[k])}`)}}`:JSON.stringify(v),hash=v=>crypto.createHash('sha256').update(canon(v)).digest('hex');
const str=(v)=>{if(typeof v!=='string')fail('PLUGIN_DATA_VALUE_NOT_STRING');return v},inside=r=>r.textBounds.x>=r.frame.x-2&&r.textBounds.y>=r.frame.y-2&&r.textBounds.x+r.textBounds.width<=r.frame.x+r.frame.width+2&&r.textBounds.y+r.textBounds.height<=r.frame.y+r.frame.height+2;
function one(a,id,code){const m=a.text(id);if(!Array.isArray(m)||m.length!==1)fail(code);return structuredClone(m[0])}
function collection(a){const c=a.collection(COLLECTION_ID);if(c.rootId!==COLLECTION_ID||c.children!==18||c.components!==18||c.cards!==4||c.texts!==38||c.validation.length||c.protected==null)fail('TEXT_COLLECTION_DRIFT');return c}
function projectTextExecutionBindingR2(a){const i=a.identity();if(i.fileId!==FILE_ID||i.pageId!==PAGE_ID||!Number.isInteger(i.revision))fail('TEXT_CURRENT_REVISION_MISSING');
 const c=collection(a),targets=TARGETS.map(s=>{const r=one(a,s.id,'TEXT_TARGET_ID_CARDINALITY');if(r.id!==s.id||r.rootId!==s.rootId||r.parentId!==s.rootId||r.characters!==s.characters||r.growType!=='fixed'||inside(r))fail('TEXT_TARGET_BASELINE_DRIFT');return {...s,frame:r.frame,textBounds:r.textBounds,growType:r.growType}});
 const protectedRows=PROTECTED.map(id=>one(a,id,'TEXT_PROTECTED_ID_CARDINALITY'));if(new Set(targets.map(x=>x.id)).size!==4||new Set(protectedRows.map(x=>x.id)).size!==16)fail('TEXT_DUPLICATE_ID');
 const all=a.managed();if(all.length!==38||new Set(all.map(x=>x.id)).size!==38)fail('TEXT_MANAGED_CENSUS_DRIFT');const offenders=all.filter(x=>!inside(x)).map(x=>x.id).sort(),expected=[...targets.map(x=>x.id),...PROTECTED].sort();if(canon(offenders)!==canon(expected))fail('TEXT_OFFENDER_SET_DRIFT');
 const p={schema:'text-binding-projection-r2',packageId:PACKAGE_ID,revision:i.revision,targets,caseRoots:TARGETS.map(x=>({caseId:x.caseId,rootId:x.rootId})),protectedRows,protectedSha:hash(protectedRows),collection:c,collectionSha:hash(c),baseline:{contained:18,managed:38,offenders:20},settled:{contained:22,managed:38,offenders:16},wholeEventcardPass:false};return {...p,projectionSha256:hash(p),penpotMutations:0}}
function auth(x,p){if(x?.schema!=='text-binding-auth-r2'||x.packageId!==PACKAGE_ID||x.parentPackageId!==PARENT_PACKAGE_ID||x.state!=='ACTIVE'||x.authorized!==true||x.cancelled!==false)fail('TEXT_AUTH_MISMATCH');if(x.revision!==p.revision)fail('TEXT_STALE_REVISION');if(x.projectionSha256!==p.projectionSha256)fail('TEXT_STALE_PROJECTION_SHA')}
async function executeTextExecutionBindingR2(a,x){if(a.marker(PACKAGE_ID))fail('TEXT_EXECUTOR_REPLAY_FORBIDDEN');const p=projectTextExecutionBindingR2(a);auth(x,p);const q=projectTextExecutionBindingR2(a);if(q.revision!==x.revision||q.projectionSha256!==x.projectionSha256)fail('TEXT_PROJECTION_CHANGED_BEFORE_MUTATION');
 const done=[];try{await a.atomic(async()=>{for(const s of TARGETS){if(a.identity().revision!==x.revision)fail('TEXT_STALE_REVISION_DURING_MUTATION');a.grow(s.id,'auto-width');a.self(s.id);await a.wait(s.id);const r=one(a,s.id,'TEXT_TARGET_ID_CARDINALITY');if(r.growType!=='auto-width'||!inside(r))fail('TEXT_SETTLEMENT_UNKNOWN',true);a.plugin(s.id,'execution-state',str('PENDING_DISTINCT_LATER_READBACK'));done.push(s.id)}})}catch(e){if(e instanceof Stop)throw e;fail('TEXT_TIMEOUT_OR_UNKNOWN_OUTCOME',true)}
 if(done.length!==4)fail('TEXT_MUTATED_ID_SET_DRIFT',true);const r={packageId:PACKAGE_ID,state:'MUTATED_PENDING_DISTINCT_LATER_READBACK',revision:x.revision,projectionSha256:x.projectionSha256,protectedSha:p.protectedSha,collectionSha:p.collectionSha,targetIds:done,mutationCount:4,next:'DISTINCT_LATER_READBACK',expected:'22/38',wholeEventcardPass:false};a.writeMarker(PACKAGE_ID,str(canon(r)));return r}
function readDistinctLaterTextBindingR2(a,r){if(r?.state!=='MUTATED_PENDING_DISTINCT_LATER_READBACK'||!a.marker(PACKAGE_ID))fail('TEXT_DISTINCT_READBACK_RECEIPT_REQUIRED');const c=collection(a);if(hash(c)!==r.collectionSha)fail('TEXT_COLLECTION_CHANGED');const t=TARGETS.map(s=>one(a,s.id,'TEXT_TARGET_ID_CARDINALITY'));if(t.some(x=>x.growType!=='auto-width'||!inside(x)))fail('TEXT_SETTLEMENT_FAILED');const p=PROTECTED.map(id=>one(a,id,'TEXT_PROTECTED_ID_CARDINALITY'));if(hash(p)!==r.protectedSha)fail('TEXT_PROTECTED_CHANGED');const all=a.managed(),off=all.filter(x=>!inside(x)).map(x=>x.id).sort();if(all.length!==38||off.length!==16||canon(off)!==canon([...PROTECTED].sort()))fail('TEXT_SETTLED_CENSUS_MISMATCH');return {state:'COMPATIBLE_OCCURRENCE_PEERS_MEASUREMENT_PASS',contained:22,offenders:16,readbackMutations:0,wholeEventcardPass:false}}
function selfTest(){class A{constructor(){this.rev=178;this.m='';this.bad=null;this.dup=null;this.timeout=false;this.token='stable';this.rows=new Map();for(const [n,s]of TARGETS.entries())this.rows.set(s.id,{id:s.id,rootId:s.rootId,parentId:s.rootId,characters:s.characters,growType:'fixed',frame:{x:n*100,y:n*100,width:120,height:16},textBounds:{x:n*100,y:n*100,width:80,height:31}});for(const [n,id]of PROTECTED.entries()){const rootId=TARGETS[n%4].rootId;this.rows.set(id,{id,rootId,parentId:'p'+n,characters:'p'+n,growType:'fixed',frame:{x:n,y:500+n,width:90,height:16},textBounds:{x:n,y:500+n,width:70,height:31}})}for(let n=0;n<18;n++){const rootId=TARGETS[n%4].rootId;this.rows.set('ok'+n,{id:'ok'+n,rootId,parentId:rootId,characters:'ok',growType:'fixed',frame:{x:n,y:n,width:100,height:30},textBounds:{x:n+1,y:n+1,width:70,height:20}})}}identity(){return{fileId:FILE_ID,pageId:PAGE_ID,revision:this.rev}}collection(){return{rootId:COLLECTION_ID,children:18,components:18,cards:4,texts:38,validation:[],protected:{token:this.token}}}text(id){if(id===this.bad)return[];const r=this.rows.get(id);return id===this.dup?[r,r]:r?[structuredClone(r)]:[]}managed(){return[...this.rows.values()].map(x=>structuredClone(x))}marker(){return this.m}writeMarker(_,v){this.m=v}async atomic(f){return f()}grow(id,v){this.rows.get(id).growType=v}self(){}async wait(id){if(this.timeout)throw Object.assign(new Error('timeout'),{code:'ETIMEDOUT'});this.rows.get(id).frame.height=40}plugin(_,__,v){str(v)}}
 const mk=p=>({schema:'text-binding-auth-r2',packageId:PACKAGE_ID,parentPackageId:PARENT_PACKAGE_ID,state:'ACTIVE',authorized:true,cancelled:false,revision:p.revision,projectionSha256:p.projectionSha256});
 let a=new A(),p=projectTextExecutionBindingR2(a);assert.equal(p.projectionSha256,projectTextExecutionBindingR2(a).projectionSha256);return executeTextExecutionBindingR2(a,mk(p)).then(r=>{assert.equal(readDistinctLaterTextBindingR2(a,r).contained,22);
 a=new A();p=projectTextExecutionBindingR2(a);a.rev++;assert.throws(()=>auth(mk(p),projectTextExecutionBindingR2(a)),e=>e.code==='TEXT_STALE_REVISION');
 a=new A();a.bad=TARGETS[0].id;assert.throws(()=>projectTextExecutionBindingR2(a),e=>e.code==='TEXT_TARGET_ID_CARDINALITY');
 a=new A();a.dup=PROTECTED[0];assert.throws(()=>projectTextExecutionBindingR2(a),e=>e.code==='TEXT_PROTECTED_ID_CARDINALITY');
 a=new A();p=projectTextExecutionBindingR2(a);const x=mk(p);a.token='changed';assert.throws(()=>auth(x,projectTextExecutionBindingR2(a)),e=>e.code==='TEXT_STALE_PROJECTION_SHA');
 a=new A();p=projectTextExecutionBindingR2(a);a.timeout=true;return executeTextExecutionBindingR2(a,mk(p)).then(()=>fail('TEST_EXPECTED_REJECTION'),e=>{assert.equal(e.code,'TEXT_TIMEOUT_OR_UNKNOWN_OUTCOME');assert.equal(e.retryAllowed,false);assert.throws(()=>str({}),e=>e.code==='PLUGIN_DATA_VALUE_NOT_STRING');console.log('TEXT_BINDING_R2_SELF_TEST_PASS 9/9')})})}
if(require.main===module&&process.argv.includes('--self-test'))selfTest().catch(e=>{console.error(e);process.exit(1)});
module.exports={PACKAGE_ID,PARENT_PACKAGE_ID,FILE_ID,PAGE_ID,COLLECTION_ID,TARGETS,PROTECTED,Stop,canon,hash,str,projectTextExecutionBindingR2,executeTextExecutionBindingR2,readDistinctLaterTextBindingR2};
