'use strict';
const crypto=require('node:crypto'),assert=require('node:assert/strict');
const PACKAGE_ID='MAT-EVENTCARD-MEDIA-COVERAGE-PROJECTION-BINDING-R2',PARENT_PACKAGE_ID='MAT-EVENTCARD-MEDIA-COVERAGE-REPAIR-R1';
const FILE_ID='40e06342-8830-80d6-8008-8fc8a3a4cd4f',PAGE_ID='c16498cb-b51d-8030-8008-904bd8fc9c53',COLLECTION_ID='313fb1ed-0d5c-8095-8008-9108df52b2ce',SLOT='event.media-frame/image-content';
const FACTS={'event.real.8006':{path:'catalog/penpot-executor/g10/input-media/dd8834258d4a1ebde029aca1960bdd224bdf636d3fd8aee8fc7824012475de8b.webp',sha:'dd8834258d4a1ebde029aca1960bdd224bdf636d3fd8aee8fc7824012475de8b',bytes:111072,w:1440,h:1920,fit:'contain',focal:'50% 50%'},'event.real.2182':{path:'catalog/fixtures/ui-reference-events/v2/assets/99d4b75ef3291c90e1457b6fdc3fe89e519b327f9d6c8ff56cd95f763e71ab1e.webp',sha:'99d4b75ef3291c90e1457b6fdc3fe89e519b327f9d6c8ff56cd95f763e71ab1e',bytes:229072,w:1280,h:853,fit:'cover',focal:'50% 50%'}};
const CASES=[['eventcard.desktop-wide-calendar.8006','313fb1ed-0d5c-8095-8008-912c45090653','event.real.8006'],['eventcard.desktop-packed-calendar-absent.2182','313fb1ed-0d5c-8095-8008-914c76615924','event.real.2182'],['eventcard.mobile-wide-calendar.8006','313fb1ed-0d5c-8095-8008-916b340de148','event.real.8006'],['eventcard.mobile-packed-calendar-absent.2182','313fb1ed-0d5c-8095-8008-916bd0ab6c98','event.real.2182']].map(([caseId,rootId,fixtureId])=>({caseId,rootId,fixtureId}));
class Stop extends Error{constructor(code,unknown=false){super(code);this.code=code;this.unknownOutcome=unknown;this.retryAllowed=false}}
const fail=(c,u=false)=>{throw new Stop(c,u)},canon=v=>Array.isArray(v)?`[${v.map(canon)}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canon(v[k])}`)}}`:JSON.stringify(v),hash=v=>crypto.createHash('sha256').update(canon(v)).digest('hex'),str=v=>{if(typeof v!=='string')fail('MEDIA_PLUGIN_DATA_NOT_STRING');return v};
function coll(a){const c=a.collection(COLLECTION_ID);if(c.rootId!==COLLECTION_ID||c.children!==18||c.components!==18||c.validation.length||c.protected==null)fail('MEDIA_COLLECTION_DRIFT');return c}
const finitePoint=(v)=>v&&Number.isFinite(v.x)&&Number.isFinite(v.y),finiteBounds=(v)=>finitePoint(v)&&Number.isFinite(v.width)&&Number.isFinite(v.height)&&v.width>0&&v.height>0;
function read(a,s){const m=a.media(s.rootId,SLOT);if(!Array.isArray(m)||m.length!==1)fail('MEDIA_ID_CARDINALITY');const r=structuredClone(a.read(m[0])),f=FACTS[s.fixtureId];if(!r.id||!r.parentId)fail('MEDIA_OR_PARENT_ID_MISSING');if(r.slot!==SLOT||!finitePoint(r.local)||!finitePoint(r.parent)||!finiteBounds(r.bounds)||!Array.isArray(r.fills)||r.fills.length<1||!r.imageData||!r.transform||!Number.isFinite(r.rotation)||typeof r.flipX!=='boolean'||typeof r.flipY!=='boolean')fail('MEDIA_FIELDS_MISSING');if(r.fit!==f.fit||r.focal!==f.focal||!r.source||r.source.sha!==f.sha||r.source.bytes!==f.bytes||r.source.path!==f.path||r.source.w!==f.w||r.source.h!==f.h)fail('MEDIA_SOURCE_OR_SEMANTICS_DRIFT');if(r.imageData.sha!==f.sha||r.imageData.bytes!==f.bytes)fail('MEDIA_IMAGEDATA_IDENTITY_DRIFT');return{caseId:s.caseId,rootId:s.rootId,fixtureId:s.fixtureId,currentMediaShapeId:r.id,currentParentOrGroupId:r.parentId,semanticMediaSlot:r.slot,localCoordinates:r.local,parentCoordinates:r.parent,bounds:r.bounds,fills:r.fills,imageDataIdentity:r.imageData,transform:r.transform,rotation:r.rotation,horizontalFlip:r.flipX,verticalFlip:r.flipY,fit:r.fit,focalPoint:r.focal,exactSourceImageIdentity:r.source}}
function projectEventcardMediaBindingR2(a){const i=a.identity();if(i.fileId!==FILE_ID||i.pageId!==PAGE_ID||!Number.isInteger(i.revision))fail('MEDIA_CURRENT_REVISION_MISSING');const c=coll(a),rows=CASES.map(s=>read(a,s));if(new Set(rows.map(x=>x.currentMediaShapeId)).size!==4)fail('MEDIA_IDS_NOT_UNIQUE');if(new Set(rows.map(x=>x.currentParentOrGroupId)).size!==4)fail('MEDIA_PARENT_IDS_NOT_UNIQUE');const p={schema:'media-projection-binding-r2',packageId:PACKAGE_ID,revision:i.revision,rows,protectedCollectionDigest:hash(c.protected),collection:c,historicalRevision63Ids:'DIAGNOSTICS_ONLY_NOT_AUTHORIZATION_INPUT',mutationFree:true};return{...p,projectionSha256:hash(p),penpotMutations:0}}
function auth(x,p){if(x?.schema!=='media-binding-auth-r2'||x.packageId!==PACKAGE_ID||x.parentPackageId!==PARENT_PACKAGE_ID||x.state!=='ACTIVE'||x.authorized!==true||x.cancelled!==false||x.parentAuthorization?.package_id!==PARENT_PACKAGE_ID)fail('MEDIA_AUTH_MISMATCH');if(x.revision!==p.revision)fail('MEDIA_STALE_REVISION');if(x.projectionSha256!==p.projectionSha256)fail('MEDIA_STALE_PROJECTION_SHA')}
async function executeEventcardMediaProjectionBindingR2(a,x,parent){if(a.marker(PACKAGE_ID))fail('MEDIA_EXECUTOR_REPLAY_FORBIDDEN');const p=projectEventcardMediaBindingR2(a);auth(x,p);let result;try{result=await a.exclusive(async()=>{const q=projectEventcardMediaBindingR2(a);if(q.revision!==x.revision||q.projectionSha256!==x.projectionSha256)fail('MEDIA_PROJECTION_CHANGED_BEFORE_MUTATION');return(parent||require('../eventcard-media-r1/eventcard_media_repair_v1.js').runEventcardMediaRepairV1)({nativeAdapter:a,executionAuthorization:x.parentAuthorization})})}catch(e){if(e instanceof Stop)throw e;fail('MEDIA_TIMEOUT_OR_UNKNOWN_OUTCOME',true)}const r={packageId:PACKAGE_ID,state:'MUTATED_PENDING_DISTINCT_LATER_READBACK',revision:x.revision,projectionSha256:x.projectionSha256,protectedCollectionDigest:p.protectedCollectionDigest,boundRows:p.rows.map(y=>({caseId:y.caseId,rootId:y.rootId,mediaId:y.currentMediaShapeId,parentId:y.currentParentOrGroupId,fixtureId:y.fixtureId})),parentResult:result,next:'DISTINCT_LATER_READBACK',retryAllowed:false,visualPass:false,wholeEventcardPass:false};a.writeMarker(PACKAGE_ID,str(canon(r)));return r}
function readDistinctLaterMediaBindingR2(a,r){if(r?.state!=='MUTATED_PENDING_DISTINCT_LATER_READBACK'||!a.marker(PACKAGE_ID))fail('MEDIA_DISTINCT_READBACK_RECEIPT_REQUIRED');const p=projectEventcardMediaBindingR2(a);if(p.protectedCollectionDigest!==r.protectedCollectionDigest)fail('MEDIA_PROTECTED_CHANGED');const old=new Map(r.boundRows.map(x=>[x.caseId,x]));for(const x of p.rows){const b=old.get(x.caseId),f=FACTS[x.fixtureId],c=a.coverage(x.currentMediaShapeId);if(!b||b.rootId!==x.rootId||b.mediaId!==x.currentMediaShapeId||b.parentId!==x.currentParentOrGroupId||x.imageDataIdentity.sha!==f.sha||x.imageDataIdentity.bytes!==f.bytes||c.status!=='KNOWN_PASS'||c.uncovered!==0||c.overlays!==0||c.sha!==f.sha)fail('MEDIA_SETTLEMENT_FAILED')}return{state:'MEDIA_PROJECTION_BOUND_READBACK_PASS_PENDING_V0',rows:4,readbackMutations:0,visualPass:false,wholeEventcardPass:false}}
function selfTest(){class A{constructor(){this.rev=178;this.m='';this.token='stable';this.missing=null;this.dup=null;this.timeout=false;this.rows=new Map();for(const[n,s]of CASES.entries()){const f=FACTS[s.fixtureId];this.rows.set(s.rootId,{id:'media'+n,parentId:'parent'+n,slot:SLOT,local:{x:n,y:n},parent:{x:100+n,y:200+n},bounds:{x:100+n,y:200+n,width:390,height:520},fills:[{fillImage:'img'+n}],imageData:{id:'img'+n,sha:f.sha,bytes:f.bytes},transform:{a:1,d:1},rotation:0,flipX:false,flipY:false,fit:f.fit,focal:f.focal,source:{path:f.path,sha:f.sha,bytes:f.bytes,w:f.w,h:f.h}})}}identity(){return{fileId:FILE_ID,pageId:PAGE_ID,revision:this.rev}}collection(){return{rootId:COLLECTION_ID,children:18,components:18,validation:[],protected:{token:this.token}}}media(root){const s=CASES.find(x=>x.rootId===root),v=this.rows.get(root);if(s.caseId===this.missing)return[];return s.caseId===this.dup?[v,v]:[v]}read(v){return v}marker(){return this.m}writeMarker(_,v){this.m=v}async exclusive(f){if(this.timeout)throw Object.assign(new Error('timeout'),{code:'ETIMEDOUT'});return f()}coverage(id){const x=[...this.rows.values()].find(y=>y.id===id);return{status:'KNOWN_PASS',uncovered:0,overlays:0,sha:x.imageData.sha}}}
 const mk=p=>({schema:'media-binding-auth-r2',packageId:PACKAGE_ID,parentPackageId:PARENT_PACKAGE_ID,state:'ACTIVE',authorized:true,cancelled:false,revision:p.revision,projectionSha256:p.projectionSha256,parentAuthorization:{package_id:PARENT_PACKAGE_ID}});
 let a=new A(),p=projectEventcardMediaBindingR2(a);assert.equal(p.projectionSha256,projectEventcardMediaBindingR2(a).projectionSha256);return executeEventcardMediaProjectionBindingR2(a,mk(p),async()=>({mutations:4})).then(r=>{assert.equal(readDistinctLaterMediaBindingR2(a,r).rows,4);
 a=new A();p=projectEventcardMediaBindingR2(a);a.rev++;assert.throws(()=>auth(mk(p),projectEventcardMediaBindingR2(a)),e=>e.code==='MEDIA_STALE_REVISION');
 a=new A();a.missing=CASES[0].caseId;assert.throws(()=>projectEventcardMediaBindingR2(a),e=>e.code==='MEDIA_ID_CARDINALITY');
 a=new A();a.dup=CASES[0].caseId;assert.throws(()=>projectEventcardMediaBindingR2(a),e=>e.code==='MEDIA_ID_CARDINALITY');
 a=new A();a.rows.get(CASES[1].rootId).id=a.rows.get(CASES[0].rootId).id;assert.throws(()=>projectEventcardMediaBindingR2(a),e=>e.code==='MEDIA_IDS_NOT_UNIQUE');
 a=new A();p=projectEventcardMediaBindingR2(a);const x=mk(p);a.token='changed';assert.throws(()=>auth(x,projectEventcardMediaBindingR2(a)),e=>e.code==='MEDIA_STALE_PROJECTION_SHA');
 a=new A();p=projectEventcardMediaBindingR2(a);a.timeout=true;return executeEventcardMediaProjectionBindingR2(a,mk(p),async()=>({})).then(()=>fail('EXPECTED'),e=>{assert.equal(e.code,'MEDIA_TIMEOUT_OR_UNKNOWN_OUTCOME');assert.equal(e.retryAllowed,false);assert.throws(()=>str({}),e=>e.code==='MEDIA_PLUGIN_DATA_NOT_STRING');console.log('MEDIA_BINDING_R2_SELF_TEST_PASS 9/9')})})}
if(require.main===module&&process.argv.includes('--self-test'))selfTest().catch(e=>{console.error(e);process.exit(1)});
module.exports={PACKAGE_ID,PARENT_PACKAGE_ID,FILE_ID,PAGE_ID,COLLECTION_ID,SLOT,FACTS,CASES,Stop,canon,hash,str,projectEventcardMediaBindingR2,executeEventcardMediaProjectionBindingR2,readDistinctLaterMediaBindingR2};
