const assert=require('assert');
const fs=require('fs');
const cp=require('child_process');
const os=require('os');
const path=require('path');
const adapter=require('../../../scripts/asp-production-conveyor-v3/f0/foundation_specimens_native_adapter_v3.js');
assert.equal(Object.keys(adapter.F0_CONFIG.domains).length,8);
assert.equal(adapter.F0_CONFIG.placements.length,57);
assert.equal(new Set(adapter.F0_CONFIG.placements.map(x=>x.id)).size,57);
assert.equal(adapter.F0_CONFIG.writer,'/root/publish_r2');
assert.equal(adapter.F0_CONFIG.fileId,'40e06342-8830-80d6-8008-8fc8a3a4cd4f');
assert.notEqual(adapter.F0_CONFIG.pageName,'00 · Components · Free collection');
assert.equal(adapter.F0_CONFIG.protectedProjectionSha256,'ae6ce7d3627f486399f1f8299690ce7f5eb25b86843a67b7970ffea00ebba2d5');
assert.deepEqual(adapter.f0PlacementXY(adapter.F0_CONFIG.placements[0]),{x:48,y:160,sectionY:112});
const source=JSON.parse(fs.readFileSync(path.join(__dirname,'../../../catalog/asp-production-conveyor-v3/f0/F-FOUNDATIONS-SPECIMENS.package.v2.json')));
assert.deepEqual(Object.keys(adapter.F0_CONFIG.domains),source.specimen_components.map(x=>x.id));
assert.deepEqual(adapter.F0_CONFIG.placements,source.materialization_entry_point.specimen.placements.map(x=>({id:x.id,componentId:x.component_id,value:x.value})));
for(const item of source.specimen_components) assert.deepEqual(adapter.F0_CONFIG.domains[item.id].values,item.id==='foundation.status'?Object.fromEntries(Object.entries(source.specimens.status_pairs).flatMap(([k,v])=>[[`${k}.surface`,v.surface],[`${k}.content`,v.content]])):source.specimens[item.value_domain]);
const active={f0FoundationRunControl:{runId:'r',leaseToken:'l',cancelToken:'c',state:'ACTIVE',cancelled:false,writer:'/root/publish_r2'}};
adapter.f0Guard(active,active.f0FoundationRunControl,'ok');
assert.throws(()=>adapter.f0Guard({f0FoundationRunControl:{...active.f0FoundationRunControl,cancelled:true}},active.f0FoundationRunControl,'cancelled'),/inactive\/cancelled/);
assert.throws(()=>adapter.f0Guard({...active,f0FoundationActiveWriter:{runId:'other',writer:'/root/publish_r2'}},active.f0FoundationRunControl,'conflict'),/sole writer conflict/);
assert.doesNotThrow(()=>adapter.f0RequireProtectedDigest({protectedDigest:adapter.F0_CONFIG.protectedProjectionSha256},adapter.F0_CONFIG.protectedProjectionSha256));
assert.throws(()=>adapter.f0RequireProtectedDigest({protectedDigest:adapter.F0_CONFIG.protectedProjectionSha256},'stale'),/stale protected projection/);
const component=(i)=>({id:`c${i}`});
const instance=(i)=>({id:`i${i}`,getSharedPluginData:()=>`p${i}`,isComponentCopyInstance:()=>true,component:()=>component(i%8)});
const census=adapter.f0VerifyCensus({components:Array.from({length:8},(_,i)=>component(i)),roots:[{id:'root'}],instances:Array.from({length:57},(_,i)=>instance(i)),screenshots:[],validation:[]});
assert.equal(census.placementIds.length,57);
assert.throws(()=>adapter.f0VerifyCensus({components:Array.from({length:8},()=>component(0)),roots:[{id:'root'}],instances:Array.from({length:57},(_,i)=>instance(i)),screenshots:[],validation:[]}),/component census mismatch/);
assert.throws(()=>adapter.f0VerifyCensus({components:Array.from({length:8},(_,i)=>component(i)),roots:[{id:'root'}],instances:Array.from({length:56},(_,i)=>instance(i)),screenshots:[],validation:[]}),/instance census mismatch/);
assert.throws(()=>adapter.f0VerifyCensus({components:Array.from({length:8},(_,i)=>component(i)),roots:[{id:'root'}],instances:Array.from({length:57},(_,i)=>instance(i)),screenshots:[{}],validation:[]}),/screenshot shape found/);
const src=fs.readFileSync(path.join(__dirname,'../../../scripts/asp-production-conveyor-v3/f0/foundation_specimens_native_adapter_v3.js'),'utf8');
for(const needle of ['f0Guard(storage,run,`component:${id}`)','f0Guard(storage,run,`placement:${placement.id}`)','f0Guard(storage,run,"post-export-before-version")','protectedBefore===protectedAfter','root.export({type:"png",scale:1})','saveVersion','maxCreatesPerCall: 3','secondRunCreated:0']) assert(src.includes(needle),needle);
const out=path.join(os.tmpdir(),`f0-native-${process.pid}.js`);
cp.execFileSync('python3',[path.join(__dirname,'../../../scripts/asp-production-conveyor-v3/f0/generate_foundation_specimens_native_executor_v3.py'),'--run-id','run-r3','--lease-token','lease-r3','--cancel-token','cancel-r3','--protected-digest','ae6ce7d3627f486399f1f8299690ce7f5eb25b86843a67b7970ffea00ebba2d5','--output',out]);
const generated=fs.readFileSync(out,'utf8'); fs.unlinkSync(out);
assert(generated.startsWith('storage.f0FoundationRunControl='));
assert(generated.includes('"state":"ACTIVE"'));
assert(generated.includes('"writer":"/root/publish_r2"'));
assert(generated.endsWith('return await runF0FoundationSpecimensV3({penpot,penpotUtils,storage});\n'));
const bad=cp.spawnSync('python3',[path.join(__dirname,'../../../scripts/asp-production-conveyor-v3/f0/generate_foundation_specimens_native_executor_v3.py'),'--run-id','run-r3','--lease-token','lease-r3','--cancel-token','cancel-r3','--protected-digest','wrong','--output',out]);
assert.notEqual(bad.status,0);
console.log('F0_FOUNDATION_NATIVE_ADAPTER_V3_TEST_PASS');
