/* Native page-split adapter for F0 foundations. Load after
 * foundation_specimens_native_adapter_v3.js and append:
 * return await runF0FoundationReviewPagesV1({penpot,storage});
 */
const B2_CONFIG=Object.freeze({
  schema:"kenigevents.f0-foundation-review-pages.v1",adapterRevision:"R1",packageId:"F-FOUNDATIONS-PAGE-SPLIT-B2",fileId:F0_CONFIG.fileId,
  writer:F0_CONFIG.writer,runId:F0_CONFIG.runId,namespace:"kenigevents-f0-page-split-b2",maxCreatesPerCall:3,
  sourceAdapterCommit:"dd2981880e2c34c19e3834b36f4f766e2c82a559",contract:{id:"kenigevents.asp-conformance",version:"1.0.0",sha256:"75c70629f01f8d60fb98290fa2e6e8abc201fc84885339c16010bcd75ddd4289"},
  source:{pageId:F0_CONFIG.pageId,rootIdSuffix:F0_CONFIG.rev106RootIdSuffix,placementCount:37,projection:{revision:113,chars:43734,utf8Bytes:43744,sha256:"523e43cfe95df7962f8034c4dc2e9f04f02114b15ad488587c707e35b6fed8f1"}},
  protectedProjection:{revision:113,chars:84033,utf8Bytes:84034,sha256:"0b00102e348367601fe35de30e06dc22b10883577a22917320955058115fc042"},
  pages:[
    {key:"colors-status",name:"03.1 · Foundations · Colors & status · Candidate",families:["foundation.colors-and-modes","foundation.status"],count:26},
    {key:"spacing-sizing",name:"03.2 · Foundations · Spacing & sizing · Candidate",families:["foundation.spacing","foundation.sizing-density"],count:14},
    {key:"shape-elevation",name:"03.3 · Foundations · Shape, borders & elevation · Candidate",families:["foundation.radius-border","foundation.elevation"],count:8},
    {key:"motion-accessibility",name:"03.4 · Foundations · Motion & accessibility · Candidate",families:["foundation.motion","foundation.accessibility"],count:9}
  ]
});
function b2Assert(ok,message){if(!ok)throw new Error(message);}
function b2Get(shape,key){return shape.getSharedPluginData(B2_CONFIG.namespace,key)||"";}
function b2Set(shape,key,value){shape.setSharedPluginData(B2_CONFIG.namespace,key,value);}
function b2Placements(spec){return F0_CONFIG.placements.filter(p=>spec.families.includes(p.componentId));}
function b2RootHeight(spec){return 112+spec.families.reduce((h,id)=>h+48+Math.ceil(b2Placements(spec).filter(p=>p.componentId===id).length/3)*152+28,0);}
function b2PlacementXY(spec,placement){let y=112;for(const id of spec.families){const rows=b2Placements(spec).filter(p=>p.componentId===id);if(id===placement.componentId){const i=rows.findIndex(p=>p.id===placement.id);return{x:48+(i%3)*448,y:y+48+Math.floor(i/3)*152,sectionY:y};}y+=48+Math.ceil(rows.length/3)*152+28;}throw new Error("B2 placement family missing");}
function b2PageMatches(page,spec){return page.name===spec.name||b2Get(page,"page-key")===spec.key;}
function b2FindPage(penpot,spec){const matches=penpot.currentFile.pages.filter(p=>b2PageMatches(p,spec));b2Assert(matches.length<=1,`duplicate review page: ${spec.key}`);const page=matches[0]||null;if(page)b2Assert(page.name===spec.name&&b2Get(page,"page-key")===spec.key,`stale page lineage forbidden: ${spec.key}`);return page;}
function b2Root(page,spec){const direct=Array.from(page.root.children||[]),matches=f0Walk(page.root).filter(s=>b2Get(s,"stable-id")===`review-root/${spec.key}`&&!ancestorIsCopy(s));b2Assert(matches.length<=1,`duplicate review root: ${spec.key}`);const root=matches[0]||null;b2Assert((!root&&direct.length===0)||(root&&direct.length===1&&direct[0].id===root.id),`foreign or stale page root forbidden: ${spec.key}`);return root;}
function b2Instances(root){return Array.from(root?.children||[]).filter(s=>b2Get(s,"placement-id"));}
function b2Sections(root){return Array.from(root?.children||[]).filter(s=>b2Get(s,"family-id"));}
function b2Census(page,spec,components,terminal=false){
  const root=b2Root(page,spec);if(!root)return{complete:false,count:0};const placements=b2Placements(spec),instances=b2Instances(root),sections=b2Sections(root),ids=instances.map(s=>b2Get(s,"placement-id"));
  b2Assert(root.parent?.id===page.root.id&&root.name===`CANDIDATE_BUILD_NOT_ACCEPTED · ${spec.name}`&&f0Near(root.width,1440)&&f0Near(root.height,b2RootHeight(spec)),`review root drift: ${spec.key}`);
  const sectionIds=sections.map(s=>b2Get(s,"family-id"));b2Assert(sections.length<=spec.families.length&&new Set(sectionIds).size===sections.length&&sectionIds.every(id=>spec.families.includes(id)),`review section duplicate or foreign: ${spec.key}`);
  b2Assert(instances.length<=spec.count&&new Set(ids).size===instances.length&&ids.every(id=>placements.some(p=>p.id===id)),`review placement duplicate or foreign: ${spec.key}`);
  b2Assert(Array.from(root.children||[]).length===sections.length+instances.length,`foreign review child forbidden: ${spec.key}`);
  for(const instance of instances){const placement=placements.find(p=>p.id===b2Get(instance,"placement-id")),xy=b2PlacementXY(spec,placement);b2Assert(instance.isComponentCopyInstance?.()&&instance.component?.()===components[placement.componentId]||instance.isComponentCopyInstance?.()&&instance.component?.()?.id===components[placement.componentId].id,`detached or wrong component: ${placement.id}`);b2Assert(f0Near(instance.x,xy.x)&&f0Near(instance.y,xy.y)&&f0Near(instance.width,416)&&f0Near(instance.height,128),`review geometry drift: ${placement.id}`);}
  const screenshots=f0Walk(root).filter(s=>s.type==="image"||Array.from(s.fills||[]).some(f=>f.fillImage));b2Assert(screenshots.length===0,`screenshot forbidden: ${spec.key}`);
  const complete=f0Canonical([...sectionIds].sort())===f0Canonical([...spec.families].sort())&&instances.length===spec.count&&f0Canonical([...ids].sort())===f0Canonical(placements.map(p=>p.id).sort());if(terminal)b2Assert(complete,`review page incomplete: ${spec.key}`);return{complete,count:instances.length,sectionCount:sections.length,placementIds:[...ids].sort(),rootId:root.id};
}
async function b2Projection(shape){const canonical=f0Canonical([f0Stable(shape)]);return{chars:canonical.length,utf8Bytes:f0Utf8(canonical).length,sha256:await f0Sha256(canonical)};}
function b2RequireProjection(actual,expected,label){b2Assert(actual.chars===expected.chars&&actual.utf8Bytes===expected.utf8Bytes&&actual.sha256===expected.sha256,`${label} projection drift: ${f0Canonical(actual)}`);}
function b2Guard(penpot,storage,operation){const receipt=f0Guard(penpot,storage,`b2:${operation}`);const provenance=storage.f0FoundationPageSplitProvenanceV1;b2Assert(provenance&&provenance.schema==="kenigevents.f0-page-split-provenance.v1"&&provenance.run_id===B2_CONFIG.runId&&provenance.writer_id===B2_CONFIG.writer&&provenance.package_id===B2_CONFIG.packageId&&provenance.adapter_revision===B2_CONFIG.adapterRevision&&provenance.source_adapter_commit===B2_CONFIG.sourceAdapterCommit&&provenance.contract_id===B2_CONFIG.contract.id&&provenance.contract_version===B2_CONFIG.contract.version&&provenance.contract_sha256===B2_CONFIG.contract.sha256&&provenance.state==="ACTIVE"&&provenance.cancelled!==true,`B2 provenance mismatch before ${operation}`);return receipt;}
function b2Write(penpot,storage,operation,callback){b2Guard(penpot,storage,operation);const block=penpot.history.undoBlockBegin();try{const result=callback();b2Assert(!(result&&typeof result.then==="function"),`async B2 mutation forbidden: ${operation}`);return result;}finally{penpot.history.undoBlockFinish(block);}}
async function b2Preflight(penpot,storage){
  b2Assert(penpot.currentFile?.id===B2_CONFIG.fileId,"wrong Penpot file");b2Guard(penpot,storage,"start");const validation=penpot.currentFile.validate();b2Assert(validation.length===0,`B2 preflight validation failed: ${f0Canonical(validation)}`);
  const protectedPage=penpot.currentFile.pages.find(p=>p.id===F0_CONFIG.protectedPageId),protectedShapes=F0_CONFIG.protectedRootIds.map(id=>protectedPage?.getShapeById(id));b2Assert(protectedPage&&protectedShapes.every(Boolean),"protected Free roots missing");const protectedActual=await f0ProtectedProjection(protectedShapes);b2RequireProjection(protectedActual,B2_CONFIG.protectedProjection,"protected Free");b2Guard(penpot,storage,"post-protected-projection");
  const sourcePage=penpot.currentFile.pages.find(p=>p.id===B2_CONFIG.source.pageId);b2Assert(sourcePage,"source/index page missing");const sourceRoots=f0FindStable(sourcePage,"root");b2Assert(sourceRoots.length===1&&f0IdEnds(sourceRoots[0],B2_CONFIG.source.rootIdSuffix),"source/index identity drift");const sourceRoot=sourceRoots[0],sourceSnapshot=f0PlacementSnapshot(sourcePage,true);b2Assert(sourceSnapshot.count===B2_CONFIG.source.placementCount,"source/index placement drift");const sourceActual=await b2Projection(sourceRoot);b2RequireProjection(sourceActual,B2_CONFIG.source.projection,"source/index");b2Guard(penpot,storage,"post-source-projection");
  const local=Array.from(penpot.library.local.components||[]),components={};for(const id of Object.keys(F0_CONFIG.domains)){const matches=local.filter(c=>f0ComponentStable(c)===id);b2Assert(matches.length===1,`canonical component missing or duplicated: ${id}`);const state=f0ComponentNamingState(matches[0],id);b2Assert(state.canonical,`canonical component naming drift: ${id}`);components[id]=matches[0];}
  return{protectedShapes,protectedActual,sourceRoot,sourceActual,sourceSnapshot,components};
}
async function b2Finalize({penpot,storage,preflight,phase,created,spec,page=null,extra={}}){
  b2Guard(penpot,storage,`finalize:${phase}:pre`);const protectedAfter=await f0ProtectedProjection(preflight.protectedShapes);b2Guard(penpot,storage,`finalize:${phase}:post-protected-await`);const sourceAfter=await b2Projection(preflight.sourceRoot);b2Guard(penpot,storage,`finalize:${phase}:post-source-await`);b2RequireProjection(protectedAfter,B2_CONFIG.protectedProjection,"protected Free");b2RequireProjection(sourceAfter,B2_CONFIG.source.projection,"source/index");b2Assert(f0Canonical(f0PlacementSnapshot(penpot.currentFile.pages.find(p=>p.id===B2_CONFIG.source.pageId),true))===f0Canonical(preflight.sourceSnapshot),"source/index placement IDs changed");let candidateReadback=null;if(page){b2Assert(page.name===spec.name&&b2Get(page,"page-key")===spec.key,`candidate page readback drift: ${spec.key}`);candidateReadback=b2Census(page,spec,preflight.components,false);}const validation=penpot.currentFile.validate();b2Assert(validation.length===0,`B2 validation failed in ${phase}: ${f0Canonical(validation)}`);b2Guard(penpot,storage,`finalize:${phase}:readback`);let versionId=null;if(created>0){const version=await penpot.currentFile.saveVersion(`F0 review pages ${B2_CONFIG.runId} · ${spec?.key||phase}`);versionId=version?.id||null;b2Guard(penpot,storage,`finalize:${phase}:version`);const durableProtected=await f0ProtectedProjection(preflight.protectedShapes);b2Guard(penpot,storage,`finalize:${phase}:durable-protected-await`);const durableSource=await b2Projection(preflight.sourceRoot);b2Guard(penpot,storage,`finalize:${phase}:durable-source-await`);b2RequireProjection(durableProtected,B2_CONFIG.protectedProjection,"durable protected Free");b2RequireProjection(durableSource,B2_CONFIG.source.projection,"durable source/index");if(page)b2Census(page,spec,preflight.components,false);b2Assert(penpot.currentFile.validate().length===0,"B2 durable validation failed");}
  return{schema:B2_CONFIG.schema,status:created>0?"RESUME_REQUIRED":"OPEN_PAGE_REQUIRED",phase,created,pageId:page?.id||null,pageKey:spec?.key||null,protectedDigest:protectedAfter.sha256,sourceDigest:sourceAfter.sha256,candidateReadback,validation,versionId,...extra};
}
function b2CreateRoot(penpot,page,spec){const root=penpot.createBoard();page.root.appendChild(root);root.name=`CANDIDATE_BUILD_NOT_ACCEPTED · ${spec.name}`;root.resize(1440,b2RootHeight(spec));root.fills=[{fillColor:"#FBF7EF",fillOpacity:1}];root.clipContent=false;root.x=0;root.y=0;b2Set(root,"stable-id",`review-root/${spec.key}`);b2Set(root,"candidate-label","CANDIDATE_BUILD_NOT_ACCEPTED");b2Set(root,"owner-review-state","NOT_ACCEPTED");return root;}
async function runF0FoundationReviewPagesV1({penpot,storage}){
  b2Assert(B2_CONFIG.pages.every(p=>p.families.length<=3&&p.count<=30&&b2Placements(p).length===p.count),"B2 page scope contract drift");const preflight=await b2Preflight(penpot,storage);let target=null;
  for(let i=0;i<B2_CONFIG.pages.length;i++){const spec=B2_CONFIG.pages[i],page=b2FindPage(penpot,spec);if(!page){b2Assert(B2_CONFIG.pages.slice(i+1).every(next=>!b2FindPage(penpot,next)),"later review page exists before current page");target={spec,page:null,index:i};break;}const census=b2Census(page,spec,preflight.components,false);if(!census.complete){b2Assert(B2_CONFIG.pages.slice(i+1).every(next=>!b2FindPage(penpot,next)),"later review page exists before current page complete");target={spec,page,index:i};break;}}
  if(!target){const exports=[];for(const spec of B2_CONFIG.pages){const page=b2FindPage(penpot,spec),census=b2Census(page,spec,preflight.components,true),root=b2Root(page,spec),raw=await root.export({type:"png",scale:1});b2Guard(penpot,storage,`terminal-export:${spec.key}`);const bytes=await f0ExportBytes(raw);b2Guard(penpot,storage,`terminal-export-bytes:${spec.key}`);b2Assert(bytes.length>0,`empty export: ${spec.key}`);const sha256=await f0Sha256(bytes);b2Guard(penpot,storage,`terminal-export-hash:${spec.key}`);exports.push({pageKey:spec.key,rootId:root.id,instances:census.count,bytes:bytes.length,sha256});}b2Guard(penpot,storage,"terminal-readback");return{schema:B2_CONFIG.schema,status:"CANDIDATE_REVIEW_PAGES_VERIFIED",created:0,secondRunCreated:0,pages:B2_CONFIG.pages.map(p=>({key:p.key,name:p.name,families:p.families,count:p.count})),exports,protectedDigest:preflight.protectedActual.sha256,sourceDigest:preflight.sourceActual.sha256,validation:[]};}
  const{spec}=target;let page=target.page,created=0;if(!page){page=b2Write(penpot,storage,`page:${spec.key}`,()=>{const value=penpot.createPage();value.name=spec.name;b2Set(value,"page-key",spec.key);b2Set(value,"candidate-label","CANDIDATE_BUILD_NOT_ACCEPTED");created++;return value;});return await b2Finalize({penpot,storage,preflight,phase:"page",created,spec,page});}
  if(penpot.currentPage?.id!==page.id)return await b2Finalize({penpot,storage,preflight,phase:"open-page",created:0,spec,page});let root=b2Root(page,spec);if(!root){root=b2Write(penpot,storage,`root:${spec.key}`,()=>{created++;return b2CreateRoot(penpot,page,spec);});return await b2Finalize({penpot,storage,preflight,phase:"root",created,spec,page});}
  for(const family of spec.families){const matches=b2Sections(root).filter(s=>b2Get(s,"family-id")===family);b2Assert(matches.length<=1,`duplicate section: ${family}`);if(!matches.length){if(created>=B2_CONFIG.maxCreatesPerCall)return await b2Finalize({penpot,storage,preflight,phase:"sections",created,spec,page});b2Write(penpot,storage,`section:${family}`,()=>{const first=b2Placements(spec).find(p=>p.componentId===family),xy=b2PlacementXY(spec,first),title=f0Text(penpot,root,`Section · ${family}`,family,48,xy.sectionY+12,18,"#221A14");b2Set(title,"family-id",family);created++;});}}
  if(created>0)return await b2Finalize({penpot,storage,preflight,phase:"sections",created,spec,page});
  for(const placement of b2Placements(spec)){const matches=b2Instances(root).filter(s=>b2Get(s,"placement-id")===placement.id);b2Assert(matches.length<=1,`duplicate review placement: ${placement.id}`);if(matches.length)continue;if(created>=B2_CONFIG.maxCreatesPerCall)return await b2Finalize({penpot,storage,preflight,phase:"instances",created,spec,page});b2Write(penpot,storage,`placement:${placement.id}`,()=>{const instance=preflight.components[placement.componentId].instance();root.appendChild(instance);const xy=b2PlacementXY(spec,placement);f0SetParentXY(instance,xy.x,xy.y);b2Set(instance,"placement-id",placement.id);b2Set(instance,"component-id",placement.componentId);f0ApplyValue(penpot,instance,placement.componentId,placement.value,F0_CONFIG.domains[placement.componentId].values[placement.value]);created++;});}
  if(created>0)return await b2Finalize({penpot,storage,preflight,phase:"instances",created,spec,page});const census=b2Census(page,spec,preflight.components,true),raw=await root.export({type:"png",scale:1});b2Guard(penpot,storage,`export:${spec.key}`);const bytes=await f0ExportBytes(raw);b2Guard(penpot,storage,`export-bytes:${spec.key}`);b2Assert(bytes.length>0,`empty export: ${spec.key}`);const sha256=await f0Sha256(bytes);b2Guard(penpot,storage,`export-hash:${spec.key}`);const exportReceipt={bytes:bytes.length,sha256};return await b2Finalize({penpot,storage,preflight,phase:"page-complete",created:0,spec,page,extra:{census,export:exportReceipt,status:"PAGE_COMPLETE_RERUN_FOR_NEXT"}});
}
if(typeof module!=="undefined"&&module.exports)module.exports={B2_CONFIG,b2Placements,b2RootHeight,b2PlacementXY,b2Census,b2RequireProjection,b2Guard,b2Write,runF0FoundationReviewPagesV1};
