export const schemaVersion = 'reconstruction-atlas-config.v1';

export const viewports = {
  mobile: { id: 'mobile-390x844', width: 390, height: 844, class: 'mobile' },
  tablet: { id: 'tablet-768x1024', width: 768, height: 1024, class: 'tablet' },
  desktop: { id: 'desktop-1280x800', width: 1280, height: 800, class: 'desktop' },
};

const sharedShell = [
  'shell.event-layout',
  'shell.desktop-header',
  'shell.mobile-header',
  'shell.mobile-menu',
  'shell.mobile-bottom-navigation',
  'shell.footer',
  'system.toast-region',
];

export const archetypes = [
  {
    id: 'archetype.home',
    checklist_label: 'Главная',
    route_patterns: ['/'],
    source_files: ['site/src/pages/index.astro'],
    representative_routes: ['/'],
    anatomy: ['home.hero-talk', 'home.quick-navigation', 'home.cold-start-feed'],
    states: ['ready', 'cold-start', 'personalized-local', 'prelaunch-env-branch'],
    responsive: ['desktop editorial hero and feed', 'mobile single-column hero, quick navigation and feed'],
    reuse: sharedShell.concat(['event.card.large', 'listing.page-pattern']),
    delta: ['home.hero-talk', 'home.quick-navigation', 'home.cold-start-feed'],
  },
  {
    id: 'archetype.listing.date',
    checklist_label: 'Листинг по дате: сегодня / завтра / произвольная дата',
    route_patterns: ['/segodnya/', '/zavtra/', '/date-:date/'],
    source_files: ['site/src/pages/segodnya/index.astro', 'site/src/pages/zavtra/index.astro', 'site/src/pages/date-[date].astro'],
    representative_routes: ['/segodnya/', '/zavtra/', '/date-2026-07-25/'],
    anatomy: ['listing.page-date-header', 'listing.discovery-rail', 'listing.controls', 'listing.time-navigation', 'listing.time-groups', 'listing.desktop-card-flow', 'listing.mobile-rail', 'listing.personal-slot'],
    states: ['today', 'tomorrow', 'specific-date', 'ready', 'sparse', 'empty', 'stress', 'completed', 'upcoming', 'now', 'untimed', 'loading', 'error'],
    responsive: ['desktop time-group grid/flow', 'mobile full-width rail rows with pinned date accessory'],
    reuse: sharedShell.concat(['listing-foundations-candidate-v1', 'listing.event-card.compact', 'listing.rail-row.track', 'listing.state-panel']),
    delta: ['listing.page-date-header', 'listing.date-weather-context', 'listing.time-navigation', 'listing.time-groups'],
  },
  {
    id: 'archetype.listing.weekend',
    checklist_label: 'Выходные',
    route_patterns: ['/vyhodnye/', '/vyhodnye/:start/'],
    source_files: ['site/src/pages/vyhodnye/index.astro', 'site/src/pages/vyhodnye/[start].astro'],
    representative_routes: ['/vyhodnye/', '/vyhodnye/2026-07-25/'],
    anatomy: ['listing.page-date-header', 'listing.weekend-range-navigation', 'listing.discovery-rail', 'listing.weekend-day-headers', 'listing.weekend-editorial-timeline', 'listing.mobile-rail', 'listing.personal-slot'],
    states: ['typical', 'sparse', 'empty', 'stress', 'current-range', 'historical-range', 'single-day-concentration', 'empty-opposite-day'],
    responsive: ['desktop two-day lanes and exact time rows', 'mobile sequential rail tracks without viewport clipping'],
    reuse: sharedShell.concat(['listing-foundations-candidate-v1', 'listing.page-pattern', 'listing.event-card.compact', 'listing.rail-row.track']),
    delta: ['listing.weekend-range-navigation', 'listing.weekend-day-header', 'listing.weekend-editorial-timeline'],
  },
  {
    id: 'archetype.listing.popular',
    checklist_label: 'Популярное',
    route_patterns: ['/populyarnoe/'],
    source_files: ['site/src/pages/populyarnoe/index.astro'],
    representative_routes: ['/populyarnoe/'],
    anatomy: ['listing.page-header', 'listing.discovery-rail', 'popular.grouping', 'popular.feed', 'listing.personal-slot'],
    states: ['ready', 'sparse', 'empty', 'personalized', 'unpersonalized', 'dense'],
    responsive: ['desktop grouped listing', 'mobile sequential rail/feed'],
    reuse: sharedShell.concat(['listing-foundations-candidate-v1', 'listing.page-pattern', 'listing.event-card.compact', 'listing.rail-row.track']),
    delta: ['popular.grouping', 'popular.trend-context'],
  },
  {
    id: 'archetype.listing.unusual',
    checklist_label: 'Необычное',
    route_patterns: ['/neobychnoe/'],
    source_files: ['site/src/pages/neobychnoe/index.astro'],
    representative_routes: ['/neobychnoe/'],
    anatomy: ['listing.page-header', 'listing.discovery-rail', 'unusual.unread-context', 'unusual.feed'],
    states: ['ready', 'empty', 'unread', 'read', 'stale', 'dense'],
    responsive: ['desktop grouped listing', 'mobile sequential feed with unread state'],
    reuse: sharedShell.concat(['listing-foundations-candidate-v1', 'listing.page-pattern', 'listing.event-card.compact']),
    delta: ['unusual.unread-context', 'unusual.status-behavior'],
  },
  {
    id: 'archetype.search',
    checklist_label: 'Поиск',
    route_patterns: ['/poisk/'],
    source_files: ['site/src/pages/poisk/index.astro'],
    representative_routes: ['/poisk/'],
    anatomy: ['search.header', 'search.query-field', 'search.filters', 'search.results', 'search.collection-links', 'search.identity-gate'],
    states: ['anonymous', 'authenticated', 'idle', 'loading', 'results', 'empty', 'error', 'retry', 'stale'],
    responsive: ['desktop search controls and result grid', 'mobile search controls and search-specific bottom navigation'],
    reuse: sharedShell.concat(['core.field', 'core.button', 'listing.event-card.compact', 'system.state-panel', 'authorization.static-site']),
    delta: ['search.query-controller', 'search.collection-links'],
  },
  {
    id: 'archetype.event-detail',
    checklist_label: 'Страница события',
    route_patterns: ['/sobytiya/:slug/'],
    source_files: ['site/src/pages/sobytiya/[slug].astro'],
    representative_routes: [
      '/sobytiya/drevnie-voiny-yantarnogo-kraya-kaliningrad-698/',
      '/sobytiya/vystavka-donbass-proshloe-i-nastoyaschee-kaliningrad-2601/',
      '/sobytiya/nauka-vsegda-kstati-progulka-s-uchenym-kaliningrad-6996/',
    ],
    anatomy: ['event.hero', 'event.media-frame', 'event.summary', 'event.admission-actions', 'event.facts', 'event.participants', 'event.venue', 'event.medallions', 'event.transport', 'event.related-events', 'event.question-cta'],
    states: ['wide-image', 'portrait-image', 'ocr-protected', 'multi-image', 'no-image', 'archived', 'calendar-present', 'calendar-absent', 'admission-present', 'admission-absent', 'transport-present', 'transport-absent'],
    responsive: ['desktop presentation resolver and editorial/split compositions', 'mobile accepted-v8 hero, continuation and action dock', 'tablet transition between branches'],
    reuse: sharedShell.concat(['event.card.large', 'event.media-frame', 'event.medallion', 'action.calendar', 'action.share', 'social-proof.like']),
    delta: ['event.detail.hero-composition', 'event.detail.facts', 'event.detail.transport', 'event.detail.related'],
  },
  {
    id: 'archetype.collections',
    checklist_label: 'Подборки: индекс и detail',
    route_patterns: ['/podborki/', '/podborki/:slug/', '/podborki/gastronomiya/'],
    source_files: ['site/src/pages/podborki/index.astro', 'site/src/pages/podborki/[slug]/index.astro', 'site/src/pages/podborki/gastronomiya/index.astro'],
    representative_routes: ['/podborki/', '/podborki/besplatnye-sobytiya/', '/podborki/dzhaz-na-vyhodnyh/', '/podborki/gastronomiya/'],
    anatomy: ['collection.index-header', 'collection.directory', 'collection.detail-header', 'collection.criteria', 'collection.results', 'collection.fallback-results', 'collection.gastronomy-surface'],
    states: ['index', 'detail-populated', 'detail-empty', 'detail-fallback', 'free-collection', 'gastronomy-editorial'],
    responsive: ['desktop editorial/result grid', 'mobile single-column result flow'],
    reuse: sharedShell.concat(['core.breadcrumbs', 'event.card.large', 'listing.state-panel']),
    delta: ['collection.directory', 'collection.criteria', 'collection.gastronomy-surface'],
  },
  {
    id: 'archetype.festivals',
    checklist_label: 'Фестивали',
    route_patterns: ['/festivali/'],
    source_files: ['site/src/pages/festivali/index.astro'],
    representative_routes: ['/festivali/'],
    anatomy: ['festival.header', 'festival.timeline', 'festival.card-flow', 'festival.category-chip'],
    states: ['ready', 'empty-period', 'theme-values', 'past', 'upcoming', 'favorite-count'],
    responsive: ['desktop calendar/timeline flow', 'mobile stacked cards and timeline'],
    reuse: sharedShell.concat(['festival.card', 'social-proof.like', 'semantic.theme-chip']),
    delta: ['festival.header', 'festival.timeline'],
  },
  {
    id: 'archetype.exhibitions',
    checklist_label: 'Выставки',
    route_patterns: ['/vystavki/'],
    source_files: ['site/src/pages/vystavki/index.astro'],
    representative_routes: ['/vystavki/'],
    anatomy: ['exhibition.header', 'exhibition.personalization', 'exhibition.rows', 'exhibition.media-deck', 'exhibition.hide-undo'],
    states: ['ready', 'personalized', 'unpersonalized', 'hidden', 'undo', 'empty', 'media-single', 'media-slider'],
    responsive: ['desktop long exhibition rows/deck', 'mobile stacked row/deck'],
    reuse: sharedShell.concat(['exhibition.row', 'event.medallion', 'social-proof.like', 'system.state-panel']),
    delta: ['exhibition.personal-surface', 'exhibition.hide-undo', 'exhibition.media-deck'],
  },
  {
    id: 'archetype.interest-clubs',
    checklist_label: 'Клубы по интересам: индекс и detail',
    route_patterns: ['/kluby-po-interesam/', '/kluby-po-interesam/:slug/'],
    source_files: ['site/src/pages/kluby-po-interesam/index.astro', 'site/src/pages/kluby-po-interesam/[slug]/index.astro'],
    representative_routes: ['/kluby-po-interesam/', '/kluby-po-interesam/game-vibes/'],
    anatomy: ['club.catalog-header', 'club.catalog-grid', 'club.card', 'club.detail-hero', 'club.detail-facts', 'club.meeting-list', 'club.empty-meetings'],
    states: ['catalog', 'detail-future-meetings', 'detail-no-future-meetings', 'cover-present', 'cover-absent'],
    responsive: ['desktop catalogue/detail grids', 'mobile single-column cards/facts/meetings'],
    reuse: sharedShell.concat(['core.breadcrumbs', 'system.state-panel']),
    delta: ['club.card', 'club.detail-facts', 'club.meeting-list'],
  },
  {
    id: 'archetype.favorites',
    checklist_label: 'Избранное',
    route_patterns: ['/izbrannoe/'],
    source_files: ['site/src/pages/izbrannoe/index.astro'],
    representative_routes: ['/izbrannoe/'],
    anatomy: ['favorites.header', 'favorites.identity-gate', 'favorites.saved-events', 'favorites.recovery'],
    states: ['anonymous', 'authenticated', 'loading', 'empty', 'populated', 'error', 'retry', 'stale'],
    responsive: ['desktop saved-event grid', 'mobile single-column saved flow'],
    reuse: sharedShell.concat(['authorization.static-site', 'event.card.large', 'listing.event-card.compact', 'system.state-panel']),
    delta: ['favorites.saved-events-controller'],
  },
  {
    id: 'archetype.personal-feed',
    checklist_label: 'Для меня / personal feed',
    route_patterns: ['/dlya-menya/'],
    source_files: ['site/src/pages/dlya-menya/index.astro'],
    representative_routes: ['/dlya-menya/'],
    anatomy: ['personal.header', 'personal.interest-profile', 'personal.filters', 'personal.feed', 'personal.feedback'],
    states: ['cold-start', 'profile-ready', 'filtered', 'reranked', 'stale', 'loading', 'empty', 'failure'],
    responsive: ['desktop profile/feed composition', 'mobile stacked profile and feed'],
    reuse: sharedShell.concat(['listing.personal-filter', 'event.card.large', 'system.state-panel', 'focus.feedback']),
    delta: ['personal.interest-profile', 'personal.rerank-controller'],
  },
  {
    id: 'archetype.focus-group',
    checklist_label: 'Фокус-группа',
    route_patterns: ['/fokus-gruppa/', '/fokus-gruppa/priglashenie/', '/fokus-gruppa/diagnostika/', '/fokus-gruppa/diagnostika-ustoychivost/', '/fokus-gruppa/kollektsiya/', '/fokus-gruppa/zavershenie/'],
    source_files: ['site/src/pages/fokus-gruppa/index.astro', 'site/src/pages/fokus-gruppa/priglashenie/index.astro', 'site/src/pages/fokus-gruppa/diagnostika/index.astro', 'site/src/pages/fokus-gruppa/diagnostika-ustoychivost/index.astro', 'site/src/pages/fokus-gruppa/kollektsiya/index.astro', 'site/src/pages/fokus-gruppa/zavershenie/index.astro'],
    representative_routes: ['/fokus-gruppa/', '/fokus-gruppa/priglashenie/', '/fokus-gruppa/diagnostika/', '/fokus-gruppa/diagnostika-ustoychivost/', '/fokus-gruppa/kollektsiya/', '/fokus-gruppa/zavershenie/'],
    anatomy: ['focus.program', 'focus.invitation-intake', 'focus.feedback', 'focus.connectivity-diagnostic', 'focus.collection', 'focus.completion'],
    states: ['program', 'invitation-loading', 'invitation-valid', 'invitation-invalid', 'diagnostic-idle', 'diagnostic-running', 'diagnostic-success', 'diagnostic-failure', 'collection-locked', 'collection-open', 'completion'],
    responsive: ['desktop research panels', 'mobile sheet/panel flow and touch targets'],
    reuse: ['focus.lab-badge', 'focus.feedback', 'focus.thank-you', 'authorization.static-site', 'system.state-panel'],
    delta: ['focus.invitation-intake', 'focus.connectivity-diagnostic', 'focus.completion'],
  },
  {
    id: 'archetype.artifacts',
    checklist_label: 'Артефакты / коллекция',
    route_patterns: ['/artefakty/'],
    source_files: ['site/src/pages/artefakty/index.astro'],
    representative_routes: ['/artefakty/'],
    anatomy: ['artifact.collection-header', 'artifact.progress', 'artifact.cards', 'artifact.reserved-slots', 'artifact.dialog'],
    states: ['empty', 'partial', 'complete', 'locked', 'unlocked', 'dialog-open'],
    responsive: ['desktop collection grid/dialog', 'mobile collection cards and bottom-sheet-like dialog'],
    reuse: sharedShell.concat(['artifact.collection-card', 'core.dialog', 'system.state-panel']),
    delta: ['artifact.collection-progress', 'artifact.unlock-dialog'],
  },
  {
    id: 'archetype.information-pages',
    checklist_label: 'Информационные, партнёрские и legal pages',
    route_patterns: ['/partners/', '/partnerstvo/', '/legal/:slug/'],
    source_files: ['site/src/pages/partners/index.astro', 'site/src/pages/partnerstvo/index.astro'],
    representative_routes: ['/partners/', '/partnerstvo/'],
    anatomy: ['information.page-header', 'information.long-form-content', 'partners.logo-grid', 'partnership.conditions', 'information.secondary-navigation'],
    states: ['partners-index', 'partnership-content', 'legal-document', 'long-content'],
    responsive: ['desktop document/content width', 'mobile readable single-column document flow'],
    reuse: sharedShell.concat(['core.breadcrumbs', 'document.typography', 'system.state-panel']),
    delta: ['partners.logo-grid', 'partnership.conditions'],
  },
  {
    id: 'archetype.special-state',
    checklist_label: 'Prelaunch, закрытая афиша и специальные недоступные состояния',
    route_patterns: ['/:home-prelaunch-env/', '/zakrytaya-afisha/', '/:unavailable/'],
    source_files: ['site/src/pages/index.astro', 'site/src/pages/zakrytaya-afisha/index.astro'],
    representative_routes: ['/zakrytaya-afisha/'],
    anatomy: ['special.prelaunch', 'special.membership-check', 'special.locked', 'special.closed-hub', 'special.unavailable'],
    states: ['prelaunch-env', 'checking', 'locked', 'hub', 'unavailable', 'noscript'],
    responsive: ['desktop special-state panel/hub', 'mobile guarded single-column state flow'],
    reuse: ['brand.identity-and-pwa', 'focus.lab-badge', 'focus.feedback', 'authorization.static-site', 'system.state-panel'],
    delta: ['special.membership-gate', 'special.closed-hub', 'special.prelaunch'],
  },
];

export const excludedProductGaps = [
  {
    id: 'route.registration',
    disposition: 'EXCLUDED_PENDING_PRODUCT_CAPABILITY',
    reason: 'The checklist explicitly forbids materializing registration until capability and source-route contract are accepted.',
  },
];
