'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const M=require('../../../../scripts/asp-production-conveyor-v3/mat/eventcard-component-paths-binding-r2/eventcard_component_paths_projection_r2.js');
class Adapter{
 constructor(){this.rev=178;this.m='';this.token='stable';this.writes=[];this.rows=M.SPECS.map((s,n)=>({id:s.componentId||'component-'+n,name:s.name,path:s.legacy?M.LEGACY:'',main:{id:s.mainId||'main-'+n,name:s.name}}));this.linkRows=new Map();for(const[n,s]of M.SPECS.slice(14).entries()){const c=this.rows[14+n],pool=n<2?this.rows.slice(0,7):this.rows.slice(7,14),use=s.links===7?pool:pool.filter((_,i)=>i!==4).slice(0,6);this.linkRows.set(c.main.id,use.map((v,i)=>({id:`linked-${n}-${i}`,componentId:v.id,parentMainId:c.main.id,parentCaseComponentId:c.id})))}}
 identity(){return{fileId:M.FILE_ID,pageId:M.PAGE_ID,revision:this.rev}}
 collection(){return{rootId:M.COLLECTION_ID,name:M.COLLECTION_NAME,roots:1,children:18,components:18,detached:0,clones:0,recreated:0,validation:[],protected:{token:this.token}}}
 components(){return structuredClone(this.rows)} links(id){return structuredClone(this.linkRows.get(id)||[])} marker(){return this.m} writeMarker(_,v){this.m=v}
 async atomic(f){return f()} setPath(id,path){this.writes.push([id,path]);this.rows.find(x=>x.id===id).path=path}
}
const auth=p=>({schema:'paths-binding-auth-r2',packageId:M.PACKAGE_ID,parentPackageId:M.PARENT_PACKAGE_ID,state:'ACTIVE',authorized:true,cancelled:false,revision:p.revision,projectionSha256:p.projectionSha256});
test('projection enumerates exact 18/18/26 current relationships',()=>{const a=new Adapter(),p=M.projectEventcardComponentPathsR2(a);assert.equal(p.revision,178);assert.equal(p.components.length,18);assert.equal(p.componentIds.length,18);assert.equal(p.mainIds.length,18);assert.equal(p.linkedInstances.length,26);assert.equal(p.linkedInstanceIds.length,26);assert.deepEqual(p.count,{exact:0,empty:15,legacy:3});for(const r of p.components){assert.ok(r.componentId&&r.mainId&&r.componentName&&r.mainName);assert.ok('currentPath'in r&&r.expectedCanonicalPath)}for(const l of p.linkedInstances){assert.ok(l.id&&l.componentId&&l.parentMainId&&l.parentCaseComponentId)}assert.equal(p.penpotMutations,0);assert.equal(p.projectionSha256,M.projectEventcardComponentPathsR2(a).projectionSha256)});
test('one bounded operation writes path only and terminal readback preserves identities/names',async()=>{const a=new Adapter(),before=M.projectEventcardComponentPathsR2(a),names=before.components.map(x=>[x.componentId,x.mainId,x.componentName,x.mainName]),r=await M.executeEventcardComponentPathsProjectionR2(a,auth(before));assert.equal(a.writes.length,18);assert.deepEqual(r.componentIds,before.componentIds);assert.deepEqual(r.mainIds,before.mainIds);assert.deepEqual(r.linkedInstanceIds,before.linkedInstanceIds);assert.deepEqual(M.projectEventcardComponentPathsR2, M.projectEventcardComponentPathsR2);const terminal=M.readEventcardComponentPathsSettlementR2(a,r);assert.equal(terminal.exact,18);assert.deepEqual(a.components().map(x=>[x.id,x.main.id,x.name,x.main.name]),names);await assert.rejects(()=>M.executeEventcardComponentPathsProjectionR2(a,auth(before)),e=>e.code==='PATHS_EXECUTOR_REPLAY_FORBIDDEN')});
test('stale revision, changed protected surface and linked ID drift fail closed',async()=>{let a=new Adapter(),p=M.projectEventcardComponentPathsR2(a);a.rev++;await assert.rejects(()=>M.executeEventcardComponentPathsProjectionR2(a,auth(p)),e=>e.code==='PATHS_STALE_REVISION');a=new Adapter();p=M.projectEventcardComponentPathsR2(a);a.token='changed';await assert.rejects(()=>M.executeEventcardComponentPathsProjectionR2(a,auth(p)),e=>e.code==='PATHS_STALE_PROJECTION_SHA');a=new Adapter();const keys=[...a.linkRows.keys()];a.linkRows.get(keys[1])[0].id=a.linkRows.get(keys[0])[0].id;assert.throws(()=>M.projectEventcardComponentPathsR2(a),e=>e.code==='PATHS_DUPLICATE_LINKED_ID')});
test('strict plugin strings',()=>{assert.throws(()=>M.str(374),e=>e.code==='PATHS_PLUGIN_DATA_NOT_STRING');assert.equal(M.str('374'),'374')});
